package org.confluence.mod.datagen;

import net.minecraft.data.PackOutput;
import net.minecraftforge.common.data.LanguageProvider;
import org.confluence.mod.Confluence;
import org.confluence.mod.block.ModBlocks;
import org.confluence.mod.effect.ModEffects;
import org.confluence.mod.entity.ModEntities;
import org.confluence.mod.item.ModItems;

import static org.confluence.mod.item.curio.CurioItems.*;

public class ModChineseProvider extends LanguageProvider {
    public ModChineseProvider(PackOutput output) {
        super(output, Confluence.MODID, "zh_cn");
    }

    @Override
    protected void addTranslations() {
        add("creativetab.confluence.accessories", "汇流来世 | 配饰");

        add("curios.tooltip.speed_boots", "穿戴者可飞速奔跑");
        add("curios.tooltip.may_fly", "可飞行");
        add("curios.tooltip.jump_boost", "增加跳跃高度");
        add("curios.tooltip.multi_jump", "可让持有者二连跳");
        add("curios.tooltip.negates_fall_damage", "消除掉落伤害");
        add("curios.tooltip.fall_resistance", "增加抗坠落性");
        add("curios.tooltip.watch", "报时");
        add("curios.tooltip.fire_immune", "对火块免疫");
        add("curios.tooltip.fluid_walk.part", "提供在水和蜂蜜上行走的能力");
        add("curios.tooltip.fluid_walk.all", "提供在水、蜂蜜、岩浆上行走的能力");
        add("curios.tooltip.lava_immune", "对岩浆免疫7秒");
        add("curios.tooltip.lava_hurt_reduce", "减少因触碰熔岩而造成的伤害");
        add("curios.tooltip.fire_attack", "近战攻击造成火焰伤害");
        add("curios.tooltip.auto_attack", "启用近战武器自动挥动");
        add("curios.tooltip.aggro_attach", "多人模式时，敌人更可能以你为目标");
        add("curios.tooltip.armor_pass", "盔甲穿透力提高%s点");
        add("curios.tooltip.projectile_attack", "远程伤害提高%s%%");
        add("curios.tooltip.compass", "显示水平位置");
        add("curios.tooltip.depth_meter", "显示深度");
        add("curios.tooltip.dps_meter", "显示你的每秒伤害");
        add("curios.tooltip.fishermans_pocket_guide", "显示钓鱼信息");
        add("curios.tooltip.life_form_analyzer", "显示您周围稀有生物的名称");
        add("curios.tooltip.metal_detector", "显示你周围最贵重的矿石");
        add("curios.tooltip.radar", "探测你周围的敌人");
        add("curios.tooltip.sextant", "显示月相");
        add("curios.tooltip.stopwatch", "显示玩家的移动速度");
        add("curios.tooltip.tally_counter", "显示怪物击杀数量");
        add("curios.tooltip.weather_radio", "显示天气");
        add("curios.tooltip.scope", "扩大远程武器的视野范围");
        add("curios.tooltip.scope2", "手持远程武器并潜行可拉远视野");
        add("curios.tooltip.wall_climb", "可爬墙，按住shift键可快速下滑");
        add("curios.tooltip.wall_slide", "可沿墙滑下，按住shift键可更快地下滑");
        add("curios.tooltip.tabi", "双击一个方向可猛冲");
        add("curios.tooltip.dodge", "有几率避开攻击");

        add("info.confluence.time", "时间: [%s:%s]");
        add("info.confluence.radar", "敌人: %s");
        add("info.confluence.compass.east", "东: %s, ");
        add("info.confluence.compass.west", "西: %s, ");
        add("info.confluence.compass.south", "南: %s");
        add("info.confluence.compass.north", "北: %s");
        add("info.confluence.depth_meter.surface", "地表: %s");
        add("info.confluence.depth_meter.underground", "地下: %s");
        add("info.confluence.tally_counter.unknown", "击杀数不可用");
        add("info.confluence.tally_counter", "已杀死 '");
        add("info.confluence.life_form_analyzer.none", "未发现稀有生物");
        add("info.confluence.life_form_analyzer", "发现稀有生物: %s");
        add("info.confluence.metal_detector.none", "未发现稀有方块");
        add("info.confluence.metal_detector", "在附近发现%s!");
        add("info.confluence.stopwatch", "速度: %s m/s");
        add("info.confluence.dps_meter", "DPS: %s");
        add("info.confluence.sextant.0", "月相: 满月");
        add("info.confluence.sextant.1", "月相: 亏凸月");
        add("info.confluence.sextant.2", "月相: 下弦月");
        add("info.confluence.sextant.3", "月相: 残月");
        add("info.confluence.sextant.4", "月相: 新月");
        add("info.confluence.sextant.5", "月相: 峨眉月");
        add("info.confluence.sextant.6", "月相: 上弦月");
        add("info.confluence.sextant.7", "月相: 盈凸月");
        add("info.confluence.weather_radio.clear", "天气: 晴天");
        add("info.confluence.weather_radio.cloudy", "天气: 阴天");
        add("info.confluence.weather_radio.rain", "天气: 下雨");
        add("info.confluence.weather_radio.snow", "天气: 下雪");
        add("info.confluence.weather_radio.thunder", "天气: 雷暴");
        add("info.confluence.fishermans_pocket_guide", "渔力: %s");

        add("key.confluence.metal_detector", "检测矿物");
        add("key.confluence.step_stool", "梯凳");

        add("curios.identifier.accessory", "配饰");
        add("curios.modifiers.accessory", "佩戴配饰时：");

        add("item.confluence.demon_heart.tooltip", "永久增加配饰栏数量");
        add("item.confluence.vitamins.tooltip", "对虚弱免疫");
        add("item.confluence.fast_clock.tooltip", "对缓慢免疫");
        add("item.confluence.blindfold.tooltip", "对失明免疫");
        add("item.confluence.trifold_map.tooltip", "对反胃免疫");
        add("item.confluence.the_plan.tooltip", "对缓慢和反胃免疫");
        add("item.confluence.holy_water.tooltip", "对凋零免疫");
        add("item.confluence.energy_bar.tooltip", "对饥饿免疫");
        add("item.confluence.flashlight.tooltip", "对黑暗免疫");
        add("item.confluence.hand_drill.tooltip", "对挖掘疲劳免疫");
        add("item.confluence.shot_put.tooltip", "对漂浮免疫");
        add("item.confluence.searchlight.tooltip", "对失明和黑暗免疫");
        add("item.confluence.detoxification_capsule.tooltip", "对中毒和凋零免疫");
        add("item.confluence.explorers_equipment.tooltip", "对挖掘疲劳和漂浮免疫");
        add("item.confluence.nutrient_solution.tooltip", "对虚弱和饥饿免疫");
        add("item.confluence.ankh_charm.tooltip", "对大部分减益免疫");
        add("item.confluence.honey_comb.tooltip", "受到伤害后释放蜜蜂并将使用者浸入蜂蜜中");
        add("item.confluence.bezoar.tooltip", "对中毒免疫");
        add("item.confluence.cobalt_shield.tooltip", "对击退免疫");
        add("item.confluence.band_of_regeneration.tooltip", "缓慢再生生命");
        add("item.confluence.magiluminescence.tooltip", "提高移动速度和加速度");
        add("item.confluence.magiluminescence.tooltip3", "“我黑暗生命中的一道短暂曙光。”");
        add("item.confluence.sandstorm_on_a_bottle.tooltip", "可让持有者更好地二连跳");
        add("item.confluence.ice_skates.tooltip", "提供额外冰面行动力");
        add("item.confluence.dunerider_boots.tooltip", "穿戴者可飞速奔跑，在沙地上还能跑得更快");
        add("item.confluence.dunerider_boots.tooltip2", "“无节律行走就不会引来蠕虫”");
        add("item.confluence.lucky_horseshoe.tooltip", "“据说能带来好运、驱除邪灵”");
        add("item.confluence.lightning_boots.tooltip", "可飞行、可飞速奔跑");
        add("item.confluence.horseshoe_balloon.tooltip", "增加跳跃高度、消除掉落伤害");
        add("item.confluence.lava_waders.tooltip2", "对火块免疫、对岩浆免疫7秒");
        add("item.confluence.bundle_of_balloons.tooltip", "可让持有者四段跳");
        add("item.confluence.bundle_of_horseshoe_balloon.tooltip", "可让持有者四段跳");
        add("item.confluence.bundle_of_horseshoe_balloon.tooltip2", "增加跳跃高度、消除掉落伤害");
        add("item.confluence.water_walking_boots.tooltip", "提供在水和蜂蜜上行走的能力");
        add("item.confluence.magma_skull.tooltip", "对火块免疫、近战攻击造成火焰伤害");
        add("item.confluence.frostspark_boots.tooltip", "可飞行、飞速奔跑、并提供额外冰面行动力");
        add("item.confluence.sun_stone.tooltip", "在白天时略微增强属性值");
        add("item.confluence.moon_stone.tooltip", "在夜晚时略微增强属性值");
        add("item.confluence.putrid_scent.tooltip", "多人模式下，敌怪不太可能以你为目标");
        add("item.confluence.panic_necklace.tooltip", "受到伤害后增加移动速度");
        add("item.confluence.paladins_shield.tooltip", "当生命值超过25%时，吸收对团队中玩家造成的25%伤害");
        add("item.confluence.frozen_shield.tooltip", "当生命值超过25%时，吸收对团队中玩家造成的25%伤害");
        add("item.confluence.frozen_shield.tooltip2", "当生命值低于50%时，在主人周围放置一个外壳，使伤害降低25%");
        add("item.confluence.frozen_turtle_shell.tooltip", "当生命值低于50%时，在主人周围放置一个外壳，使伤害降低25%");
        add("item.confluence.fire_gauntlet.tooltip", "增加近战击退并使攻击附着火焰伤害");
        add("item.confluence.cross_necklace.tooltip", "增加受到伤害后的无敌时间");
        add("item.confluence.terraspark_boots.tooltip2", "对火块免疫并在7秒内对熔岩免疫");
        add("item.confluence.fledgling_wings.tooltip", "提供飞行的能力");
        add("item.confluence.worm_scarf.tooltip", "所受伤害减少17%");
        add("item.confluence.shield_of_cthulhu.tooltip", "允许冲刺，疾跑以冲刺");
        add("item.confluence.brain_of_confusion.tooltip", "有几率制造幻觉并躲避攻击");
        add("item.confluence.brain_of_confusion.tooltip2", "闪避后暂时增加暴击几率");
        add("item.confluence.brain_of_confusion.tooltip3", "被击中后可能会迷惑附近的敌人");
        add("item.confluence.royal_gel.tooltip", "史莱姆将变成友好生物");
        add("item.confluence.arcane_flower.tooltip3", "敌人不太可能以你为目标");
        add("item.confluence.celestial_stone.tooltip", "小幅提高属性值");
        add("item.confluence.charm_of_myths.tooltip", "提供生命恢复，减少治疗药水的冷却时间");
        add("item.confluence.philosophers_stone.tooltip", "减少治疗药水的冷却时间");
        add("item.confluence.gravity_globe.tooltip", "可让持有者反转重力");
        add("item.confluence.gravity_globe.tooltip2", "按跳跃键可改变重力");
        add("item.confluence.ancient_chisel.tooltip2", "“古老的问题需要古老的解决方案”");
        add("item.confluence.flower_boots.tooltip", "你走过的草地上会长出花朵");
        add("item.confluence.treasure_magnet.tooltip", "扩大物品拾取范围");
        add("item.confluence.hand_warmer.tooltip", "对寒冷和冰冻效果免疫");
        add("item.confluence.star_cloak.tooltip", "受到伤害后会使星星坠落");
        add("item.confluence.hive_pack.tooltip", "增加友好蜜蜂的力量");
        add("item.confluence.sweetheart_necklace.tooltip", "受到伤害后释放蜜蜂并将使用者浸入蜂蜜中、并提高移动速度");
        add("item.confluence.magic_quiver.tooltip2", "20%几率不消耗箭");
        add("item.confluence.molten_quiver.tooltip", "点燃木箭，火光熊熊");
        add("item.confluence.molten_quiver.tooltip2", "“在恐惧中颤抖吧！”");
        add("item.confluence.recon_scope.tooltip", "“发现敌人”");
        add("item.confluence.portable_cement_mixer.tooltip", "右键点击延迟降低1");
        add("item.confluence.brick_layer.tooltip", "右键点击延迟降低1");
        add("item.confluence.architect_gizmo_pack.tooltip", "右键点击延迟降低2，且降低效果不能与其材料的降低效果叠加");
        add("item.confluence.climbing_claws.tooltip", "结合鞋钉使用时能力还会有所提升");
        add("item.confluence.shoe_spikes.tooltip", "结合攀爬爪使用时能力还会有所提升");
        add("item.confluence.frog_gear.tooltip", "“身为绿皮生物可太难了”");
        add("item.confluence.hand_of_creation.tooltip2", "右键点击延迟降低3，且降低效果不能与其材料的降低效果叠加");
        add("item.confluence.step_stool.tooltip", "按↑键站得更高，按Shift键下来");
        add("item.confluence.step_stool.tooltip2", "额外高度：%s");
        add("item.confluence.magic_mirror.tooltip", "盯着镜子便可回家");
        add("item.confluence.cell_phone.tooltip", "显示所有信息");
        add("item.confluence.cell_phone.tooltip2", "可随意回家");

        add("item.confluence.aglet.info", "金属带扣是能提升玩家移动速度的配饰");
        add("item.confluence.aglet.info2", "它出现在沉船宝箱中");
        add("item.confluence.amber_horseshoe_balloon.info", "琥珀马掌气球是个配饰，能增加跳跃高度、让玩家免疫掉落伤害、并在被攻击时释放会寻找并伤害敌怪的蜜蜂。");
        add("item.confluence.amber_horseshoe_balloon.info2", "能给予运气加成。");
        add("item.confluence.amber_horseshoe_balloon.info3", "它可以在工作台处用幸运马掌和蜂蜜气球制作。");
        add("item.confluence.amphibian_boots.info", "水陆两用靴是一种配饰，它可以在工作台处用旗鱼靴和蛙腿制作。");
        add("item.confluence.amphibian_boots.info2", "提高玩家的最大移动速度");// 英文待改
        add("item.confluence.amphibian_boots.info3", "允许自动跳跃");
        add("item.confluence.amphibian_boots.info4", "提高跳跃速度");
        add("item.confluence.anklet_of_the_wind.info", "疾风脚镯是一种配饰，为移动速度提供加成。");
        add("item.confluence.anklet_of_the_wind.info2", "其效果和金属带扣的移动速度奖励可以叠加。");
        add("item.confluence.anklet_of_the_wind.info3", "它可以在工作台处用孢子花和藤蔓制作。");
        add("item.confluence.blizzard_in_a_balloon.info", "它使跳跃高度、跳跃速度提高、并允许二段跳。");    // 气球通用    英文待改
        add("item.confluence.blizzard_in_a_balloon.info2", "它可以在工作台处用暴雪瓶和闪亮红气球制作。");
        add("item.confluence.blizzard_in_a_bottole.info", "暴风瓶是配饰，其工作原理类似于云朵瓶，允许玩家进行二段跳。");
        add("item.confluence.blizzard_in_a_bottole.info2", "它可以在工作台处用云朵瓶和蓝冰制作。");
        add("item.confluence.blue_horseshoe_balloon.info", "蓝色马蹄气球是一种配饰，佩戴后可以免疫坠落伤害，增加跳跃高度，允许二段跳，并提供 +0.05 的幸运。");  // 马蹄气球通用
        add("item.confluence.blue_horseshoe_balloon.info2", "它可以在工作台处用云朵气球和幸运马掌制作。");
        add("item.confluence.bundle_of_balloons.info", "气球束是一种配饰，可让佩戴者进行四段跳，并将玩家的跳跃持续时间增加，跳跃速度增加。");
        add("item.confluence.bundle_of_balloons.info2", "它可以在工作台处用云朵气球、沙暴气球、暴雪气球制作。");
        add("item.confluence.bundle_of_horseshoe_balloons.info", "马掌气球束是一种结合了气球束和幸运马掌功能的配饰。");
        add("item.confluence.bundle_of_horseshoe_balloons.info2", "装备后，玩家可以进行四段跳，并将玩家的跳跃持续时间增加，跳跃速度增加，运气增加 0.05%。");
        add("item.confluence.bundle_of_horseshoe_balloons.info3", "装备它还可以防止玩家受到坠落伤害。");
        add("item.confluence.bundle_of_horseshoe_balloons.info4", "它可以在工作台处用气球束和幸运马掌制作。");
        add("item.confluence.cloud_in_a_balloon.info", "云朵气球是一种配饰，结合了云朵瓶和闪亮红气球的功能。");
        add("item.confluence.cloud_in_a_balloon.info2", "它使跳跃高度、跳跃速度提高、并允许二段跳。");
        add("item.confluence.cloud_in_a_balloon.info3", "它可以在工作台处用云朵瓶和闪亮红气球制作。");
        add("item.confluence.cloud_in_a_bottle.info", "云朵瓶是一种配饰，可以在矿井和地牢的宝箱中找到。");
        add("item.confluence.cloud_in_a_bottle.info2", "装备后，佩戴者可以进行二段跳");
        add("item.confluence.dunerider_boots.info", "沙丘行者靴是一种可以提高玩家最大移动速度的配饰");
        add("item.confluence.dunerider_boots.info2", "它有几率从尸壳中掉落。");
        add("item.confluence.dunerider_boots.info3", "提高玩家的最大移动速度");
        add("item.confluence.dunerider_boots.info4", "在任何沙子、砂岩上移动时，提高最大移动速度，加强加速和减速变化");
        add("item.confluence.fairy_boots.info", "仙灵靴是一种配饰，它可以在工作台处用幽灵靴和花靴制作");
        add("item.confluence.fairy_boots.info2", "他们将这两种效果结合到一双靴子中。");
        add("item.confluence.fart_in_a_balloon.info", "臭屁气球是一个配饰，结合了罐中臭屁和闪亮红气球的效果。");
        add("item.confluence.fart_in_a_balloon.info2", "它使跳跃高度、跳跃速度提高、并允许二段跳。");
        add("item.confluence.fart_in_a_balloon.info3", "与大多数其他二段跳气球不同，臭屁气球完全跳跃的高度足以让玩家受到轻微的坠落伤害，除非玩家有像幸运马掌这样的坠落伤害免疫配饰。 ");
        add("item.confluence.fart_in_a_balloon.info4", "它可以在工作台处用罐中臭屁和闪亮红气球制作。");
        add("item.confluence.fart_in_a_jar.info", "罐中臭屁是一种配饰，佩戴者可以进行二段跳");
        add("item.confluence.flipper.info", "脚蹼是一种配饰，可以让玩家在液体中游泳。当脚蹼装备在配件槽中时，玩家可以通过反复按住或按下跳跃键，在水、熔岩或蜂蜜中向上游动——基本上允许在液体中无限次跳跃。");
        add("item.confluence.flipper.info2", "它出现在沉船宝箱中");
        add("item.confluence.flurry_boots.info", "疾风雪靴是一种可以在雪地小屋找到的配饰。");
        add("item.confluence.flurry_boots.info2", "提高玩家的最大移动速度");
        add("item.confluence.frog_flipper.info", "青蛙脚蹼是由蛙腿和脚蹼在工作台上制成的配饰。");
        add("item.confluence.frog_flipper.info2", "它结合了这两个配饰的能力，增加了玩家的跳跃速度和安全坠落距离，允许自动跳跃，并赋予玩家游泳的能力。");
        add("item.confluence.frog_leg.info", "蛙腿有几率从青蛙掉落。");
        add("item.confluence.frog_leg.info2", "提高玩家的跳跃速度");
        add("item.confluence.frog_leg.info3", "此效果也适用于攀岩爪和其他攀爬配件。");
        add("item.confluence.frog_leg.info4", "最大安全坠落距离增加 10");
        add("item.confluence.frostspark_boots.info", "霜花靴是将闪电靴和溜冰鞋组合在工作台上制作的配饰。");
        add("item.confluence.frostspark_boots.info2", "它提供了两者的效果。");
        add("item.confluence.green_horseshoe_balloon.info", "绿马蹄气球是一个配饰，它使跳跃高度、跳跃速度提高、并允许二段跳。");
        add("item.confluence.green_horseshoe_balloon.info2", "它可以在工作台处用臭屁气球和幸运马掌制作。");
        add("item.confluence.hand_warmer.info", "暖手器是一种免疫配饰，可赋予玩家对冰冻和冰冻减益的免疫力。");
        add("item.confluence.hand_warmer.info2", "它可以在工作台处用羊毛和皮革制作。");
        add("item.confluence.hermes_boots.info", "赫尔墨斯靴是一种配饰，可以在村庄盔甲匠的宝箱中找到。");
        add("item.confluence.hermes_boots.info2", "装备后，它们允许玩家在连续奔跑一定距离后获得移动速度提升。");
        add("item.confluence.honey_balloon.info", "蜂蜜气球是一款结合了闪亮红色气球和蜂窝功能的配件。");
        add("item.confluence.honey_balloon.info2", "它使跳跃高度、跳跃速度提高，并在玩家受伤时释放一小群愤怒的蜜蜂，它们会寻找并对敌人造成少量伤害。");
        add("item.confluence.honey_balloon.info3", "它可以在工作台处用闪亮红气球和蜂窝制作。");
        add("item.confluence.ice_skates.info", "溜冰鞋是配饰，可以提高玩家在所有冰块上的移动控制。");
        add("item.confluence.ice_skates.info2", "玩家加速更快，滑行距离更短，并且在坠落或跳跃着陆时不再导致薄冰破裂。");
        add("item.confluence.ice_skates.info3", "它可以在工作台处用赫尔墨斯靴和蓝冰制作。");
        add("item.confluence.lava_charm.info", "熔岩护身符是一种配饰，可以免疫熔岩 7 秒。");
        add("item.confluence.lava_charm.info2", "它有几率从烈焰人中掉落。");
        add("item.confluence.lava_waders.info", "熔岩靴是一种配饰，允许玩家在所有液体的表面上行走，包括水和熔岩，而不会受到熔岩伤害或触发着火（与水上行走靴和黑曜石水上行走靴不同，它们只允许在水上行走）。");
        add("item.confluence.lava_waders.info2", "熔岩靴还允许玩家安全地浸入熔岩中 7 秒，而不会受到熔岩伤害或触发着火。");
        add("item.confluence.lava_waders.info3", "所有液体，包括熔岩，都可以在熔岩靴装备时无限期地行走。");
        add("item.confluence.lava_waders.info4", "倒计时只适用于淹没在熔岩中的情况，而玩家可以无限期地站在熔岩表面。");
        add("item.confluence.lightning_boots.info", "闪电靴是一种配饰，其功能与幽灵靴基本相同，但运行速度更快。");
        add("item.confluence.lightning_boots.info2", "它可以在工作台处用幽灵靴，疾风脚镯和金属带扣制作。");
        add("item.confluence.lucky_horseshoe.info", "幸运马掌是一个配饰，可以抵消坠落伤害并给予+0.05点幸运。");
        add("item.confluence.lucky_horseshoe.info2", "它可以在沙漠神殿、末地城、丛林神庙或古代城内的宝箱中找到。");
        add("item.confluence.magiluminescence.info", "魔光护符是配饰，可将玩家的最大移动速度提高，提高玩家的加速和减速");
        add("item.confluence.magiluminescence.info2", "它可以在末地城的宝箱中找到。");
        add("item.confluence.magiluminescence.info3", "这种增加与赫尔墨斯靴及其变种的加成叠加。");
        add("item.confluence.magiluminescence.info4", "当玩家不接地时，魔光护符的移动速度增益会被禁用。");
        add("item.confluence.magma_skull.info", "岩浆骷髅头是免疫配饰，可使玩家免疫造成燃烧减益的方块，并给予熔岩免疫 7 秒。");
        add("item.confluence.magma_skull.info2", "它可以在工作台处用黑曜石骷髅头和熔岩护身符制作");
        add("item.confluence.molten_charm.info", "熔火护身符是由熔岩护身符和黑曜石骷髅头制成的配饰，结合了这两种物品的效果。");
        add("item.confluence.molten_charm.info2", "熔火护身符还可以免疫通常因接触岩浆块而造成的燃烧伤害。");// 需改英文
        add("item.confluence.molten_charm.info3", "它不能免疫其他火焰伤害");
        add("item.confluence.obsidian_horseshoe.info", "黑曜石马掌是一种结合了幸运马掌和黑曜石骷髅头功能的配饰。");
        add("item.confluence.obsidian_horseshoe.info2", "它对岩浆块造成的燃烧伤害给予免疫，抵消坠落伤害并给予+0.05点幸运。");
        add("item.confluence.obsidian_horseshoe.info3", "但是，它不提供黑曜石骷髅头提供的额外 1 点防御。");
        add("item.confluence.obsidian_horseshoe.info4", "它可以在工作台处用幸运马掌和黑曜石骷髅头制作。");
        add("item.confluence.obsidian_water_walking_boots.info", "黑曜石水上漂靴是一种结合了水上漂靴和黑曜石骷髅头能力的配饰。");
        add("item.confluence.obsidian_water_walking_boots.info2", "它们允许佩戴者在水上行走，同时还对燃烧减益免疫。");
        add("item.confluence.obsidian_water_walking_boots.info3", "他们不允许在熔岩上行走。");
        add("item.confluence.obsidian_water_walking_boots.info4", "它可以在工作台处用水上漂靴和黑曜石骷髅头制作");
        add("item.confluence.pink_horseshoe_balloon.info", "粉红马蹄气球是一个配饰，可以免疫坠落伤害，增加跳跃高度和跳跃速度，提供二段跳，并给予+0.05的运气。");
        add("item.confluence.pink_horseshoe_balloon.info2", "它可以在工作台处用鲨鱼龙气球和幸运马掌制作。");
        add("item.confluence.rocket_boots.info", "火箭靴是一种配饰，可让玩家飞行约 1.6 秒（100 个游戏帧）。");
        add("item.confluence.rocket_boots.info2", "它们需要从半空中跳跃才能激活（二段跳，或坠落时跳跃）。");
        add("item.confluence.rocket_boots.info3", "它可以在工作台处用铁锭,铁靴和烈焰弹制作。");
        add("item.confluence.sailfish_boots.info", "旗鱼靴是一种允许玩家加速的配饰。");
        add("item.confluence.sailfish_boots.info2", "它可以在沉船宝箱中找到.");
        add("item.confluence.sailfish_boots.info3", "装备后，它们允许玩家在连续奔跑一定距离后获得速度提升。");
        add("item.confluence.sandstorm_in_a_balloon.info", "沙暴气球是一种结合了沙暴瓶和闪亮红气球功能的配饰。");
        add("item.confluence.sandstorm_in_a_balloon.info2", "它可以在工作台处用沙暴瓶和闪亮红气球制作。");
        add("item.confluence.sandstorm_in_a_balloon.info3", "它使跳跃高度、跳跃速度提高、并允许二段跳。");
        add("item.confluence.sandstorm_in_a_bottle.info", "沙暴瓶是一种配饰，可以在沙漠神殿的宝箱中找到。");
        add("item.confluence.sharkron_balloon.info", "鲨鱼龙气球是一个结合了海啸瓶和气球河豚鱼效果的配饰。");
        add("item.confluence.sharkron_balloon.info2", "它使跳跃高度、跳跃速度提高。");
        add("item.confluence.shiny_red_balloon.info", "闪亮红气球是一个配饰，它使跳跃高度、跳跃速度提高。");
        add("item.confluence.shiny_red_balloon.info2", "当玩家拥有村庄英雄效果时，图书管理员有几率将此物品交给玩家。");
        add("item.confluence.spectre_boots.info", "幽灵靴是由 火箭靴 和 疾风雪靴、赫尔墨斯靴、沙丘行者靴或 旗鱼靴制成的配饰，并结合了它们的功能。");
        add("item.confluence.terraspark_boots.info", "泰拉闪耀靴是配饰，它可以在工作台处用霜花靴和熔岩靴制作。提供这两种物品的效果。");
        add("item.confluence.terraspark_boots.info2", "它们是 疾风雪靴、赫尔墨斯靴、沙丘行者靴、旗鱼靴和水上漂靴的最终升级。");
        add("item.confluence.tsunami_in_a_bottle.info", "海啸瓶是一种配饰，可以在沉船宝箱中找到");
        add("item.confluence.tsunami_in_a_bottle.info2", "与云朵瓶类似，它允许玩家进行二段跳。");
        add("item.confluence.water_walking_boots.info", "水上漂靴是一种配饰，可让玩家在水、蜂蜜和微光上行走。");
        add("item.confluence.water_walking_boots.info2", "玩家以正常速度在这些液体中移动而不会下沉。");
        add("item.confluence.water_walking_boots.info3", "它可以在海洋废墟宝箱中找到。");
        add("item.confluence.white_horseshoe_balloon.info", "白马掌气球是一个配饰，它使跳跃高度、跳跃速度提高、并允许二段跳。并给予+0.05的运气。");
        add("item.confluence.white_horseshoe_balloon.info2", "它可以在工作台处用暴雪瓶和闪亮红气球制作。");
        add("item.confluence.yellow_horseshoe_balloon.info", "黄马掌气球是一个配饰，它使跳跃高度、跳跃速度提高、并允许二段跳。并给予+0.05的运气。");
        add("item.confluence.yellow_horseshoe_balloon.info2", "它可以在工作台处用沙暴瓶和闪亮红气球制作。");
        add("item.confluence.copper_watch.info", "铜表是一种低级表。");
        add("item.confluence.copper_watch.info2", "当装备到配饰栏或者放在物品栏时，游戏内的时间（精确到一小时）就会以表的形式显示在屏幕的右上角。");
        add("item.confluence.copper_watch.info3", "它可以在工作台处用红石粉，铜锭，锁链制作。");
        add("item.confluence.tin_watch.info", "锡表是一种低级表。");
        add("item.confluence.tin_watch.info2", "当装备到配饰栏或者放在物品栏时，游戏内的时间（精确到一小时）就会以表的形式显示在屏幕的右上角。");
        add("item.confluence.tin_watch.info3", "它可以在工作台处用红石粉，锡锭，锁链制作。");
        add("item.confluence.silver_watch.info", "银表是一种中级表。");
        add("item.confluence.silver_watch.info2", "当装备到配饰栏或者放在物品栏时，游戏内的时间（精确到半小时）就会以表的形式显示在屏幕的右上角。");
        add("item.confluence.silver_watch.info3", "它可以在工作台处用红石粉，银锭，锁链制作。");
        add("item.confluence.tungsten_watch.info", "钨表是一种中级表。");
        add("item.confluence.tungsten_watch.info2", "当装备到配饰栏或者放在物品栏时，游戏内的时间（精确到半小时）就会以表的形式显示在屏幕的右上角。");
        add("item.confluence.tungsten_watch.info3", "它可以在工作台处用红石粉，钨锭，锁链制作。");
        add("item.confluence.gold_watch.info", "金表是一种高级表。铂金表是它的替代品。");
        add("item.confluence.gold_watch.info2", "当装备到配饰栏或者放在物品栏时，游戏内的时间（精确到分钟）就会以表的形式显示在屏幕的右上角。");
        add("item.confluence.gold_watch.info3", "它可以在工作台处用红石粉，金锭，锁链制作。");
        add("item.confluence.platinum_watch.info", "铂金表是一种高级表。");
        add("item.confluence.platinum_watch.info2", "当装备到配饰栏或者放在物品栏时，游戏内的时间（精确到分钟）就会以表的形式显示在屏幕的右上角。");
        add("item.confluence.platinum_watch.info3", "它可以在工作台处用红石粉，铂金锭，锁链制作。");
        add("item.confluence.depth_meter.info", "深度计是一种信息配饰，可显示玩家的深度。");
        add("item.confluence.depth_meter.info2", "深度计有几率从蝙蝠身上掉落。");
        add("item.confluence.compass.info", "指南针是一种信息配饰，可以在装备后在屏幕上显示玩家的横向位置。");
        add("item.confluence.compass.info2", "指南针有几率从蝙蝠身上掉落。");
        add("item.confluence.dps_meter.info", "每秒伤害计数器是一种信息配件，可显示上次对任何实体造成伤害的武器的 DPS。");
        add("item.confluence.dps_meter.info2", "深度计有几率从爬行者（苦力怕）身上掉落。");
        add("item.confluence.fishermans_pocket_guide.info", "渔民袖珍指南是一个信息配饰，显示玩家当前的捕鱼能力。");
        add("item.confluence.fishermans_pocket_guide.info2", "这件物品可以在渔夫村民家中的箱子中找到。");
        add("item.confluence.fish_finder.info", "探鱼器是一个信息配饰，提供渔民袖珍指南显示的信息，该指南显示玩家当前的捕鱼能力，天气收音机显示当前天气，六分仪显示月亮的当前相位。");
        add("item.confluence.fish_finder.info2", "它可以在工作台处用渔民袖珍指南，天气收音机，六分仪制作。");
        add("item.confluence.goblin_tech.info", "哥布林数据仪是一个信息配饰，是秒表、每秒伤害计数器和金属探测器的组合，显示附近最有价值的物品、您当前的 DPS 和您的速度。");
        add("item.confluence.goblin_tech.info2", "它可以在工作台处用秒表，每秒伤害计数器，金属探测器制作。");
        add("item.confluence.life_form_analyzer.info", "生命体分析机是一种信息配件，可以显示玩家周围 47.5 米范围内的稀有敌人、小动物的名字。");
        add("item.confluence.life_form_analyzer.info2", "生命体分析仪有几率从荧光鱿鱼身上掉落。");
        add("item.confluence.metal_detector.info", "金属探测器是一种信息配饰，可以检测玩家周围 47.5 米范围内的贵重物品，包括矿石、箱子、生命水晶和生命果实。");
        add("item.confluence.metal_detector.info2", "金属探测器有几率从坚守者身上掉落。");
        add("item.confluence.pda.info", "个人数字助手是一种结合了其成分功能的配件，显示钓鱼信息、天气、月相、海拔、东西距离、时间、最近的贵重宝藏、移动速度、当前 DPS、杀死的敌人数量、附近稀有生物和附近敌人的数量。");
        add("item.confluence.pda.info2", "它可以在工作台处用全球定位系统，哥布林数据仪，R.E.K. 3000，探鱼器制作。");
        add("item.confluence.radar.info", "雷达是一种信息配件，可显示玩家周围 63.5 米半径内附近敌人的数量。");
        add("item.confluence.radar.info2", "雷达有几率从蝙蝠身上掉落。");
        add("item.confluence.rek_3000.info", "R.E.K. 3000 是后骷髅王的信息配饰，提供有关附近敌人数量、玩家击杀敌人数量和附近稀有生物的信息。");
        add("item.confluence.rek_3000.info2", "T它可以在工作台处用杀怪计数器，雷达，生命体分析机制作。");
        add("item.confluence.sextant.info", "六分仪是一种显示当前月相的信息配饰。");
        add("item.confluence.sextant.info2", "这件物品可以在渔夫村民家中的箱子中找到。");
        add("item.confluence.stopwatch.info", "秒表是一种信息配件，可以显示玩家当前的移动速度，以英里/小时为单位。");
        add("item.confluence.stopwatch.info2", "它可以在工作台处用红石粉，铁锭锭，锁链制作。");
        add("item.confluence.tally_counter.info", "杀怪计数器是骷髅王之后的信息配饰，可以显示某种类型的敌人被杀死了多少。");
        add("item.confluence.tally_counter.info2", "杀怪计数器有几率从爬行者（苦力怕）身上掉落。");
        add("item.confluence.weather_radio.info", "天气收音机是一种信息配饰，可以显示地表上的当前天气和风速，即使玩家在地下、洞穴或地下世界图层中也是如此。");
        add("item.confluence.weather_radio.info2", "这件物品可以在渔夫村民家中的箱子中找到。");
        add("item.confluence.band_of_regeneration.info", "再生手环是一个有几率从女巫身上掉落的配饰");
        add("item.confluence.band_of_regeneration.info2", "装备后，它每秒恢复 0.2 点生命值。");
        add("item.confluence.angler_earring.info", "渔夫耳环是一种配饰，装备后可使玩家当前的钓鱼能力增加 10。");
        add("item.confluence.angler_earring.info2", "这件物品可以在渔夫村民家中的箱子中找到。");
        add("item.confluence.brain_of_confusion.info", "混沌之脑是一个配饰，在装备时受到伤害时，附近的敌人有 3/5 （60%） 的几率获得控脑术减益，持续至少 1.5 秒。");
        add("item.confluence.brain_of_confusion.info2", "混乱之脑有几率从僵尸村民身上掉落。");
        add("item.confluence.gravity_globe.info", "重力球是一种配饰，允许持有者翻转重力，使玩家向上而不是向下坠落，然后将重力切换回正常状态。");
        add("item.confluence.gravity_globe.info2", "重力球有几率从潜影贝中掉落。");
        add("item.confluence.hive_pack.info", "蜜蜂背包是一个配件，装备后，有 1/2 （50%） 的几率用更大的“巨型蜜蜂”替换友方蜜蜂射弹。");
        add("item.confluence.hive_pack.info2", "蜜蜂背包有几率从蜜蜂身上掉落。");
        add("item.confluence.royal_gel.info", "皇家凝胶是配饰，装备后可以安抚大多数史莱姆，使它们不再追击玩家，并且不会造成接触伤害或发射射弹，即使玩家对它们造成伤害。");
        add("item.confluence.royal_gel.info2", "皇家凝胶有几率从史莱姆中掉落。");
        add("item.confluence.shield_of_cthulhu.info", "克苏鲁之盾是盾牌配饰，允许玩家通过双击左键或右键来执行冲刺攻击。");
        add("item.confluence.shield_of_cthulhu.info2", "它有几率从劫掠兽身上掉落。");
        add("item.confluence.worm_scarf.info", "蠕虫围巾是配饰，可减少 17% 的伤害。");
        add("item.confluence.worm_scarf.info2", "当玩家有一只被驯服的猫时，猫可能会在玩家醒来时给玩家这个物品。");
        add("item.confluence.ancient_chisel.info", "远古凿子是一种配饰，可将采矿速度提高 25%。");
        add("item.confluence.ancient_chisel.info2", "该物品可以通过考古获得。");
        add("item.confluence.architect_gizmo_pack.info", "建筑师工具包是一种配饰，可以提高方块和墙壁的放置速度和范围，并自动绘制放置的物体，基本上赋予用于制作它的配件的所有效果。");
        add("item.confluence.architect_gizmo_pack.info2", "它可以在工作台处用砌砖刀，加长握爪，便携式水泥搅拌机，喷漆机制作。");
        add("item.confluence.brick_layer.info", "砌砖刀是一种配饰，在放置方块、家具和任何其他可放置物品时，可将玩家的放置速度提高 50%。");
        add("item.confluence.brick_layer.info2", "这件物品可以在工具匠村民家中的箱子中找到。");
        add("item.confluence.extendo_grip.info", "加长握爪是一种配饰，可将区块开采和放置范围延长 3 米。");
        add("item.confluence.extendo_grip.info2", "它可以在沙漠神殿内的箱子中找到。");
        add("item.confluence.portable_cement_mixer.info", "便携式水泥搅拌机是一种配饰，可将玩家放置背景墙的速度提高 50%。");
        add("item.confluence.portable_cement_mixer.info2", "这件物品可以在工具匠村民家中的箱子中找到。");
        add("item.confluence.toolbelt.info", "工具腰带是一个配饰，可以将方块的放置范围增加一米。");
        add("item.confluence.toolbelt.info2", "这件物品可以在工具匠村民家中的箱子中找到。");
        add("item.confluence.toolbox.info", "工具箱可以放在工具匠村民家中的箱子里。");
        add("item.confluence.toolbox.info2", "它使方块放置和工具范围增加 1");
        add("item.confluence.flower_boots.info", "花靴是一种稀有的配饰，当玩家在草地上行走时，它会使花朵生长。");
        add("item.confluence.flower_boots.info2", "花靴有几率从苔藓块掉落。");
        add("item.confluence.treasure_magnet.info", "宝藏磁铁是一种配饰，装备后可将物品的拾取范围增加到 6.25 米。");
        add("item.confluence.treasure_magnet.info2", "它可以在沙漠神殿、末地城、丛林神庙或古代城内的宝箱中找到。");
        add("item.confluence.ankh_charm.info", "十字章护身符是一款免疫配饰，结合了解毒囊、营养液、计划书、探照灯和探险家宝具的效果");
        add("item.confluence.ankh_charm.info2", "这件物品可以在工作台上使用护甲支架、药用绷带、计划书、反诅咒咒语和反光阴影制作。");  // 待改
        add("item.confluence.ankh_shield.info", "十字章护盾 是一种护盾和免疫配饰，可提供对10种不同减益的免疫、击退免疫和额外的4种防御。");
        add("item.confluence.ankh_shield.info2", "它可以在工作台处用黑曜石盾，十字章护身符制作。");
        add("item.confluence.avenger_emblem.info", "复仇者勋章是一种配饰，可使所有武器的伤害增加 12%。");
        add("item.confluence.bee_cloak.info", "蜜蜂斗篷是配饰，结合了星星斗篷和蜂窝的效果。");
        add("item.confluence.bee_cloak.info2", "当玩家受伤时，三颗星星会落在玩家的当前位置，蜜蜂会被释放。");
        add("item.confluence.bee_cloak.info3", "它可以在带有蜂窝和星星斗篷的制作台上制作。");
        add("item.confluence.berserkers_glove.info", "狂战士手套是由泰坦手套和血肉指关节制作的配饰，具有两者的能力。");
        add("item.confluence.berserkers_glove.info2", "可使近战武器和鞭能够自动挥舞");
        add("item.confluence.bezoar.info", "牛黄是一种免疫配饰，可赋予玩家对中毒减益的免疫力。");
        add("item.confluence.bezoar.info2", "它有几率从洞穴蜘蛛中掉落。");
        add("item.confluence.black_belt.info", "黑腰带是一种配饰，有 10% 的几率躲避攻击，包括从陷阱和熔岩等危险中受到的伤害。 ");
        add("item.confluence.black_belt.info2", "它有几率从凋零骷髅中掉落。");
        add("item.confluence.blindfold.info", "蒙眼布是一种免疫配饰，可使玩家对失明减益产生免疫力。");
        add("item.confluence.blindfold.info2", "它可以在古代城内的箱子中找到。");
        add("item.confluence.celestial_stone.info", "天界石是用月亮石和太阳石在工作台上制成的配饰");
        add("item.confluence.celestial_stone.info2", "它提供与其组件相同的提升，因此，它在白天和晚上都处于活动状态。");
        add("item.confluence.cobalt_shield.info", "钴盾是一种护盾配饰，装备后可使玩家免疫击退，并提供 1 点防御。");
        add("item.confluence.cobalt_shield.info2", "它有几率从劫掠兽身上掉落。");
        add("item.confluence.cross_necklace.info", "十字项链是一种配饰，可使玩家在受到伤害后获得的无敌持续时间翻倍，从大约 0.67 秒增加到大约 1.33 秒。");
        add("item.confluence.cross_necklace.info2", "它有几率从唤魔者身上掉落。");
        add("item.confluence.detoxification_capsule.info", "解毒囊是一种配饰，可使玩家对中毒减益和凋零减益产生免疫力。");
        add("item.confluence.detoxification_capsule.info2", "它可以在带有牛黄和圣水的工作台上制作。");
        add("item.confluence.energy_bar.info", "能量条是一种配饰，可使玩家对饥饿减益免疫。");
        add("item.confluence.energy_bar.info2", "它有几率从僵尸猪灵身上掉落。");
        add("item.confluence.explorers_equipment.info", "探险家宝具是一种配件，可赋予玩家对中毒减益和凋零减益的免疫力。");
        add("item.confluence.explorers_equipment.info2", "它可以在工作台上用手钻和铅球制作。");
        add("item.confluence.eye_of_the_golem.info", "石巨人之眼是配饰，可提供+10%的暴击率。");
        add("item.confluence.eye_of_the_golem.info2", "它可以在丛林神庙内的箱子中找到。");
        add("item.confluence.fast_clock.info", "快走时钟是一种免疫配饰，可赋予玩家对慢速减益的免疫力。");
        add("item.confluence.fast_clock.info2", "它有几率从流浪者中掉落。");
        add("item.confluence.feral_claws.info", "狂爪手套是一种配件，可以将近战攻击速度提高 12%，并与所有其他攻击速度提升叠加。");
        add("item.confluence.feral_claws.info2", "它可以在丛林神庙内的箱子中找到。");
        add("item.confluence.fire_gauntlet.info", "烈火手套是一种配饰，可增强近战武器");
        add("item.confluence.flashlight.info", "探险家宝具是一种配饰，可赋予玩家对黑暗减益的免疫力。");
        add("item.confluence.flashlight.info2", "它可以在要塞内的箱子中找到。");
        add("item.confluence.flesh_knuckles.info", "血肉指虎是一种配件，可使玩家的防御力提高 8 点，仇恨值提高 400 点。");
        add("item.confluence.flesh_knuckles.info2", "它有几率从猪灵蛮兵身上掉落。");
        add("item.confluence.frozen_shield.info", "冰冻护盾是一个配件。");
        add("item.confluence.frozen_shield.info2", "它会将对队友造成的一些伤害重定向到玩家身上，将防御力提高 6 点，赋予击退免疫力，并在玩家生命值较低时为玩家提供伤害吸收护盾。");
        add("item.confluence.frozen_shield.info3", "它可以在带有圣骑士盾牌和冰冻龟壳的工作台上制作。");
        add("item.confluence.frozen_turtle_shell.info", "冰冻海龟壳是一种配饰，只要他们的生命值保持在 50% 或以下，它就会获得冰障增益，从而提供 25% 的伤害减免。");
        add("item.confluence.frozen_turtle_shell.info2", "当海龟因冰冻而死时，有几率掉落了这个饰品。");
        add("item.confluence.hand_drill.info", "手钻是一种配件，可使玩家免疫采矿疲劳减益。");
        add("item.confluence.hand_drill.info2", "它有几率从远古守护者身上掉落。");
        add("item.confluence.hero_shield.info", "英雄护盾是一种配饰，可以在生命值高于 25% 的情况下重定向来自同一团队的玩家的 25% 伤害，类似于圣骑士盾");
        add("item.confluence.hero_shield.info2", "它可以在带有圣骑士盾和血肉指虎的工作台上制作。");
        add("item.confluence.holy_water.info", "圣水是一种配饰，可赋予玩家对凋零减益的免疫力。");
        add("item.confluence.holy_water.info2", "它有几率从凋零骷髅中掉落。");
        add("item.confluence.honey_comb.info", "蜂窝是一种配饰，装备后会生成 1-3 个（或装备蜂巢包时生成 1-4 个）蜜蜂射弹，每次玩家受到伤害时都会攻击附近的敌人。");
        add("item.confluence.honey_comb.info2", "它还会在受到伤害后提供蜂蜜增益，持续 5 秒。");
        add("item.confluence.honey_comb.info3", "它有几率从蜜蜂身上掉落。");
        add("item.confluence.magic_quiver.info7", "这件物品有几率从凋零骷髅中掉落。");
        add("item.confluence.magma_stone.info", "岩浆石是从烈焰人掉落的配件。");
        add("item.confluence.magma_stone.info2", "它使佩戴者的近战攻击对敌人造成着火。");
        add("item.confluence.mechanical_glove.info", "机械手套是一种配饰，可使所有近战武器的击退翻倍，并将近战伤害和速度提高 12%。");
        add("item.confluence.mechanical_glove.info2", "它可以在带有强力手套和复仇者勋章的工作台上制作。");
        add("item.confluence.molten_quiver.info", "熔火箭袋是一种配饰，具有与魔法箭袋相同的效果，只是在从弓箭发射时将木箭变成火焰箭。");
        add("item.confluence.molten_quiver.info2", "它可以在带有魔法箭袋和岩浆石的工作台上制作。");
        add("item.confluence.molten_skull_rose.info", "熔火骷髅玫瑰是代表黑曜石骷髅头最终升级的配件。");
        add("item.confluence.molten_skull_rose.info2", "它提供 7 秒的熔岩免疫力、火焰方块免疫力，并减少熔岩造成的伤害。");
        add("item.confluence.molten_skull_rose.info3", "它可以在工作台上使用黑曜石骷髅玫瑰和熔岩护身符，或岩浆骷髅头和黑曜石玫瑰，或岩浆骷髅头和黑曜石骷髅玫瑰制作。");
        add("item.confluence.moon_stone.info", "月亮石是一个配饰，有几率从幻翼掉落");
        add("item.confluence.moon_stone.info2", "它提供与太阳石相同的属性加成，但这些加成只会在夜间激活。");
        add("item.confluence.nutrient_solution.info", "营养液是一种配饰，可使玩家对虚弱减益和饥饿减益产生免疫力");
        add("item.confluence.nutrient_solution.info2", "它可以在带有维生素和能量棒的工作台上制作。");
        add("item.confluence.obsidian_rose.info", "黑曜石玫瑰是一种配件，可将从熔岩中获取的基础伤害减半。");
        add("item.confluence.obsidian_rose.info2", "它可以在堡垒遗迹中发现的箱子中发现。");
        add("item.confluence.obsidian_shield.info", "黑曜石盾牌是由钴盾和黑曜石骷髅头制成的盾牌配饰，结合了它们的功能和防御提升。");
        add("item.confluence.obsidian_shield.info2", "它提供击退免疫，以及燃烧减益的免疫，并提供 2 点防御。");
        add("item.confluence.obsidian_skull.info", "黑曜石骷髅头是一种免疫配饰，可免疫通常通过接触陨石、狱石和狱石砖块造成的燃烧减益。");
        add("item.confluence.obsidian_skull.info2", "它还提供 1 个防御。");
        add("item.confluence.obsidian_skull.info3", "它可以在工作台上使用黑曜石和凋零骷髅头制作。");
        add("item.confluence.obsidian_skull_rose.info", "黑曜石骷髅玫瑰是由黑曜石骷髅头和黑曜石玫瑰制成的配饰，结合了它们的功能，赋予对火焰块的免疫力并减少熔岩的伤害。");
        add("item.confluence.paladins_shield.info", "圣骑士盾是一种主要在多人游戏中起作用的配饰。");
        add("item.confluence.paladins_shield.info2", "装备后，当佩戴者的生命值高于 25% 时，它会为其团队中所有附近的玩家提供圣骑士之盾增益：该增益会使对他们造成的任何伤害的 25% 转移到护盾佩戴者身上。");
        add("item.confluence.paladins_shield.info3", "在单人游戏和多人游戏中，圣骑士盾牌还为佩戴者提供了对击退的免疫力，并提供额外的 6 点防御。");
        add("item.confluence.paladins_shield.info4", "它将从末影龙中掉落。");
        add("item.confluence.panic_necklace.info", "恐慌项链是一种配饰，装备后，玩家将获得恐慌！当受到火焰方块以外的任何伤害源的伤害时，增益 8 秒，移动速度提高 100%。");
        add("item.confluence.panic_necklace.info2", "它可以在地牢中的宝箱中找到。");
        add("item.confluence.power_glove.info", "强力手套是一种配饰，可使近战击退加倍，并增加 12% 的近战速度。");
        add("item.confluence.power_glove.info2", "它可以在制作台上使用泰坦手套和狂爪手套制作。");
        add("item.confluence.putrid_scent.info", "它可以在地牢中的宝箱中找到。");
        add("item.confluence.ranger_emblem.info", "游侠徽章是配件，可增加15%的远程伤害。");
        add("item.confluence.ranger_emblem.info2", "它有几率从凋零骷髅中掉落。");
        add("item.confluence.rifle_scope.info", "它有几率从末影人身上掉落。");
        add("item.confluence.searchlight.info", "探照灯是一种配件，可使玩家免疫 黑暗 和 失明 。");
        add("item.confluence.shackle.info", "镣铐是一种提供 1 点防御的配饰。");
        add("item.confluence.shackle.info2", "它可以在地牢中的宝箱中找到。");
        add("item.confluence.shark_tooth_necklace.info", "鲨牙项链是一种配件，有几率从溺尸身上掉落。");
        add("item.confluence.shot_put.info", "铅球是一种配件，可使玩家对漂浮减益产生免疫力。");
        add("item.confluence.shot_put.info2", "它可以在要塞的宝箱中找到。");
        add("item.confluence.sniper_scope.info", "狙击镜是一种配件，可提供 10% 的远程伤害增加和 10% 的远程暴击率。");
        add("item.confluence.sorcerer_emblem.info", "巫师徽章是配件，可增加15%的魔法伤害。");
        add("item.confluence.sorcerer_emblem.info2", "它有几率从唤魔者身上掉落。");
        add("item.confluence.star_cloak.info", "星星斗篷是一种配饰，每当玩家受到伤害时，它就会使三颗星星落在玩家周围。");
        add("item.confluence.star_cloak.info2", "它可以在林地府邸内的箱子中找到。");
        add("item.confluence.star_veil.info", "星星面纱是一种结合了星星斗篷和十字项链功能的配饰，可以生成流星弹，并增加玩家受伤时获得的无敌帧的长度。");
        add("item.confluence.star_veil.info2", "它可以在工作台上使用星星斗篷和十字架项链制作。");
        add("item.confluence.sun_stone.info", "太阳石是一个配饰，有几率被烈焰人掉落。");
        add("item.confluence.sweetheart_necklace.info", "甜心项链是一种配饰，可以释放出集中的蜜蜂爆发并赋予玩家恐慌！和蜂蜜增益时受到伤害，移动速度提高 100%，持续 8 秒，生命恢复 5 秒。");
        add("item.confluence.sweetheart_necklace.info2", "它可以在工作台上使用蜂窝和恐慌项链制作。");
        add("item.confluence.the_plan.info", "计划书是一个免疫配饰，结合了快走时钟和三折地图的功能，赋予对慢速和恶心减益的免疫。");
        add("item.confluence.the_plan.info2", "它可以在制作台上使用快走时钟和三折地图制作。");
        add("item.confluence.titan_glove.info", "泰坦手套是一种配饰，可以使玩家造成的近战击退加倍。");
        add("item.confluence.titan_glove.info2", "它可以在废弃矿井的宝箱中找到。");
        add("item.confluence.trifold_map.info", "三折地图是一种配饰，可赋予玩家对恶心减益的免疫力。");
        add("item.confluence.trifold_map.info2", "它可以在要塞图书馆的宝箱中找到。");
        add("item.confluence.vitamins.info", "维生素是一种配饰，可使玩家对虚弱减益产生免疫力。");
        add("item.confluence.vitamins.info2", "它有几率从女巫身上掉落。");
        add("item.confluence.warrior_emblem.info", "战士徽章是一种可增加15%近战伤害的配件。");
        add("item.confluence.warrior_emblem.info2", "它有几率从卫道士身上掉落。");
        add("item.confluence.demon_heart.info", "它必定从凋零身上掉落。");
        add("item.confluence.climbing_claws.info", "它有几率从蜘蛛身上掉落。");
        add("item.confluence.shoe_spikes.info", "它有几率从洞穴蜘蛛中掉落。");
        add("item.confluence.tabi.info", "它可以在要塞的宝箱中找到。");
        add("item.confluence.step_stool.info", "你可以在锻造台使用梯凳升级它的额外高度");

        add("death.attack.star_cloak", "%1$s 被坠星压扁了");

        add("attribute.name.generic.critical_chance", "暴击率");
        add("attribute.name.generic.ranged_velocity", "远程速度");
        add("attribute.name.generic.ranged_damage", "远程伤害");
        add("attribute.name.generic.dodge_chance", "闪避率");
        add("attribute.name.generic.mining_speed", "挖掘速率");
        add("attribute.name.generic.aggro", "仇恨");
        add("attribute.name.generic.magic_damage", "魔法伤害");
        add("attribute.name.generic.armor_pass", "护甲穿透");
        add("attribute.name.generic.pickup_range", "拾取范围");

        add("container.confluence.workshop", "工匠作坊");
        add("title.confluence.workshop", "工匠作坊");

        add("achievements.confluence.boots_of_the_hero.title", "英雄之靴");
        add("achievements.confluence.boots_of_the_hero.description", "获得泰拉闪耀靴，这是用最好的火靴和最好的冰靴铸成的。");

        add(ModEffects.PALADINS_SHIELD.get(), "圣骑士护盾");
        add(ModEffects.CEREBRAL_MINDTRICK.get(), "控脑术");
        add(ModEffects.CONFUSED.get(), "困惑");
        add(ModEffects.HONEY.get(), "蜂蜜");
        add(ModEffects.GRAVITATION.get(), "重力反转");

        add(ModItems.DEMON_HEART.get(), "恶魔之心");

        // 饰品
        add(AGLET.get(), "金属带扣");
        add(ANKLET_OF_THE_WIND.get(), "疾风脚镯");
        add(CLOUD_IN_A_BOTTLE.get(), "云朵瓶");
        add(SHACKLE.get(), "脚镣");
        add(EXTENDO_GRIP.get(), "加长握爪");
        add(BLIZZARD_IN_A_BOTTLE.get(), "暴雪瓶");
        add(ICE_SKATES.get(), "溜冰鞋");
        add(HERMES_BOOTS.get(), "赫尔墨斯靴");
        add(FLURRY_BOOTS.get(), "疾风雪靴");
        add(SAILFISH_BOOTS.get(), "旗鱼靴");
        add(DUNERIDER_BOOTS.get(), "沙丘行者靴");
        add(ROCKET_BOOTS.get(), "火箭靴");
        add(SPECTRE_BOOTS.get(), "幽灵靴");
        add(LIGHTNING_BOOTS.get(), "闪电靴");
        add(FROSTSPARK_BOOTS.get(), "霜花靴");
        add(SHINY_RED_BALLOON.get(), "闪亮红气球");
        add(CLOUD_IN_A_BALLOON.get(), "云朵气球");
        add(BLIZZARD_IN_A_BALLOON.get(), "暴雪气球");
        add(FROG_LEG.get(), "蛙腿");
        add(AMBHIPIAN_BOOTS.get(), "水陆两用靴");
        add(LUCKY_HORSESHOE.get(), "幸运马掌");
        add(BEZOAR.get(), "牛黄");
        add(BLACK_BELT.get(), "黑腰带");
        add(MAGILUMINESCENCE.get(), "魔光护符");
        add(FLIPPER.get(), "脚蹼");
        add(SANDSTORM_IN_A_BOTTLE.get(), "沙暴瓶");
        add(FART_IN_A_JAR.get(), "罐中臭屁");
        add(SANDSTORM_IN_A_BALLOON.get(), "沙暴气球");
        add(FART_IN_A_BALLOON.get(), "臭屁气球");
        add(FROG_FLIPPER.get(), "青蛙脚蹼");
        add(BLUE_HORSESHOE_BALLOON.get(), "蓝马掌气球");
        add(WHITE_HORSESHOE_BALLOON.get(), "白马掌气球");
        add(YELLOW_HORSESHOE_BALLOON.get(), "黄马掌气球");
        add(GREEN_HORSESHOE_BALLOON.get(), "绿马掌气球");
        add(BLINDFOLD.get(), "蒙眼布");
        add(AVENGER_EMBLEM.get(), "复仇者勋章");
        add(COBALT_SHIELD.get(), "钴护盾");
        add(CROSS_NECKLACE.get(), "十字项链");
        add(DESTROYER_EMBLEM.get(), "毁灭者勋章");
        add(EYE_OF_THE_GOLEM.get(), "石巨人之眼");
        add(PINK_HORSESHOE_BALLOON.get(), "粉马掌气球");
        add(SHARKRON_BALLOON.get(), "鲨鱼龙气球");
        add(BALLOON_PUFFERFISH.get(), "气球河豚鱼");
        add(TSUNAMI_IN_A_BOTTLE.get(), "海啸瓶");
        add(MAGMA_SKULL.get(), "岩浆骷髅头");
        add(LAVA_CHARM.get(), "熔岩护身符");
        add(OBSIDIAN_ROSE.get(), "黑曜石玫瑰");
        add(OBSIDIAN_SHIELD.get(), "黑曜石护盾");
        add(OBSIDIAN_SKULL.get(), "黑曜石骷髅头");
        add(MOLTEN_SKULL_ROSE.get(), "熔火骷髅头玫瑰");
        add(OBSIDIAN_SKULL_ROSE.get(), "黑曜石骷髅头玫瑰");
        add(COPPER_WATCH.get(), "铜表");
        add(TIN_WATCH.get(), "锡表");
        add(SILVER_WATCH.get(), "银表");
        add(TUNGSTEN_WATCH.get(), "钨表");
        add(GOLD_WATCH.get(), "金表");
        add(PLATINUM_WATCH.get(), "铂金表");
        add(PALADINS_SHIELD.get(), "圣骑士护盾");
        add(RADAR.get(), "雷达");
        add(DEPTH_METER.get(), "深度计");
        add(COMPASS.get(), "罗盘");
        add(FERAL_CLAWS.get(), "狂爪手套");
        add(FIRE_GAUNTLET.get(), "烈火手套");
        add(FLESH_KNUCKLES.get(), "血肉指虎");
        add(POWER_GLOVE.get(), "强力手套");
        add(PUTRID_SCENT.get(), "腐香囊");
        add(MOLTEN_CHARM.get(), "熔火护身符");
        add(WATER_WALKING_BOOTS.get(), "水上漂靴");
        add(OBSIDIAN_WATER_WALKING_BOOTS.get(), "黑曜石水上漂靴");
        add(LAVA_WADERS.get(), "熔岩靴");
        add(TERRASPARK_BOOTS.get(), "泰拉闪耀靴");
        add(OBSIDIAN_HORSESHOE.get(), "黑曜石马掌");
        add(BERSERKERS_GLOVE.get(), "狂战士手套");
        add(TITAN_GLOVE.get(), "泰坦手套");
        add(TALLY_COUNTER.get(), "杀怪计数器");
        add(BUNDLE_OF_BALLOONS.get(), "气球束");
        add(BUNDLE_OF_HORSESHOE_BALLOONS.get(), "马掌气球束");
        add(FROZEN_TURTLE_SHELL.get(), "冰冻海龟壳");
        add(FROZEN_SHIELD.get(), "冰冻护盾");
        add(HERO_SHIELD.get(), "英雄护盾");
        add(MOON_STONE.get(), "月亮石");
        add(SUN_STONE.get(), "太阳石");
        add(MECHANICAL_GLOVE.get(), "机械手套");
        add(PANIC_NECKLACE.get(), "恐慌项链");
        add(MAGMA_STONE.get(), "岩浆石");
        add(METAL_DETECTOR.get(), "金属探测器");
        add(STOPWATCH.get(), "秒表");
        add(REK_3000.get(), "R.E.K.3000");
        add(LIFE_FORM_ANALYZER.get(), "生命体分析机");
        add(DPS_METER.get(), "每秒伤害计数器");
        add(FISHERMANS_POCKET_GUIDE.get(), "渔民袖珍宝典");
        add(WEATHER_RADIO.get(), "天气收音机");
        add(SEXTANT.get(), "六分仪");
        add(GPS.get(), "全球定位系统");
        add(GOBLIN_TECH.get(), "哥布林数据仪");
        add(FISH_FINDER.get(), "探鱼器");
        add(PDA.get(), "个人数字助手");
        add(SHARK_TOOTH_NECKLACE.get(), "鲨牙项链");
        add(CELESTIAL_STONE.get(), "天界石");
        add(FAST_CLOCK.get(), "快走时钟");
        add(SORCERER_EMBLEM.get(), "巫师徽章");
        add(ANCIENT_CHISEL.get(), "远古凿子");
        add(ROYAL_GEL.get(), "皇家凝胶");
        add(SHIELD_OF_CTHULHU.get(), "克苏鲁护盾");
        add(WORM_SCARF.get(), "蠕虫围巾");
        add(BRAIN_OF_CONFUSION.get(), "混乱之脑");
        add(VITAMINS.get(), "维生素");
        add(GRAVITY_GLOBE.get(), "重力球");
        add(WARRIOR_EMBLEM.get(), "战士徽章");
        add(TREASURE_MAGNET.get(), "宝藏磁石");
        add(FLOWER_BOOTS.get(), "花靴");
        add(FAIRY_BOOTS.get(), "仙灵靴");
        add(RANGER_EMBLEM.get(), "游侠徽章");
        add(HAND_WARMER.get(), "暖手宝");
        add(STAR_CLOAK.get(), "星星斗篷");
        add(STAR_VEIL.get(), "星星面纱");
        add(BEE_CLOAK.get(), "蜜蜂斗篷");
        add(HIVE_PACK.get(), "蜂巢背包");
        add(HONEY_COMB.get(), "蜂窝");
        add(STINGER_NECKLACE.get(), "毒刺项链");
        add(SWEETHEART_NECKLACE.get(), "甜心项链");
        add(HONEY_BALLOON.get(), "蜂蜜气球");
        add(AMBER_HORSESHOE_BALLOON.get(), "琥珀马掌气球");
        add(MAGIC_QUIVER.get(), "魔法箭袋");
        add(MOLTEN_QUIVER.get(), "熔火箭袋");
        add(STALKERS_QUIVER.get(), "潜行者箭袋");
        add(BAND_OF_REGENERATION.get(), "再生手环");
        add(ANGLER_EARRING.get(), "渔夫耳环");
        add(HOLY_WATER.get(), "圣水");
        add(DETOXIFICATION_CAPSULE.get(), "解毒囊");
        add(ENERGY_BAR.get(), "能量棒");
        add(NUTRIENT_SOLUTION.get(), "营养液");
        add(FLASHLIGHT.get(), "手电筒");
        add(SEARCHLIGHT.get(), "探照灯");
        add(TRIFOLD_MAP.get(), "三折地图");
        add(THE_PLAN.get(), "计划书");
        add(HAND_DRILL.get(), "手钻");
        add(SHOT_PUT.get(), "铅球");
        add(EXPLORERS_EQUIPMENT.get(), "探险家宝具");
        add(ANKH_CHARM.get(), "十字章护身符");
        add(ANKH_SHIELD.get(), "十字章护盾");
        add(RIFLE_SCOPE.get(), "步枪瞄准镜");
        add(SNIPER_SCOPE.get(), "狙击镜");
        add(RECON_SCOPE.get(), "侦察镜");
        add(TOOLBELT.get(), "工具腰带");
        add(TOOLBOX.get(), "工具箱");
        add(PORTABLE_CEMENT_MIXER.get(), "便携式水泥搅拌机");
        add(BRICK_LAYER.get(), "砌砖刀");
        add(ARCHITECT_GIZMO_PACK.get(), "建筑师发明背包");
        add(CLIMBING_CLAWS.get(), "攀爬爪");
        add(SHOE_SPIKES.get(), "鞋钉");
        add(TIGER_CLIMBING_GEAR.get(), "猛虎攀爬装备");
        add(TABI.get(), "分趾厚底袜");
        add(MASTER_NINJA_GEAR.get(), "忍者大师装备");
        add(FROG_WEBBING.get(), "青蛙蹼");
        add(FROG_GEAR.get(), "青蛙装备");
        add(STEP_STOOL.get(), "梯凳");
        add(HAND_OF_CREATION.get(), "创造之手");
        add(ModItems.MAGIC_MIRROR.get(), "魔镜");
        add(ModItems.CELL_PHONE.get(), "手机");

        add(ModEntities.BEE_PROJECTILE.get(), "蜜蜂射弹");
        add(ModEntities.STAR_CLOAK.get(), "坠星");
        add(ModEntities.STEP_STOOL.get(), "梯凳");

        add(ModBlocks.WORKSHOP.get(), "工匠作坊");
    }
}
