package org.confluence.mod.datagen;

import net.minecraft.data.PackOutput;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.WallSignBlock;
import net.minecraft.world.level.block.WallTorchBlock;
import net.minecraftforge.common.data.LanguageProvider;
import org.confluence.mod.Confluence;
import org.confluence.mod.block.ModBlocks;
import org.confluence.mod.capability.prefix.ModPrefix;
import org.confluence.mod.datagen.limit.CustomName;
import org.confluence.mod.effect.ModEffects;
import org.confluence.mod.entity.ModEntities;
import org.confluence.mod.item.ModItems;

import java.util.Arrays;
import java.util.stream.Collectors;

public class ModEnglishProvider extends LanguageProvider {
    public ModEnglishProvider(PackOutput output) {
        super(output, Confluence.MODID, "en_us");
    }

    private static String toTitleCase(String raw) {
        return Arrays.stream(raw.split("_"))
                .map(word -> Character.toUpperCase(word.charAt(0)) + word.substring(1).toLowerCase())
                .collect(Collectors.joining(" "));
    }

    @Override
    protected void addTranslations() {
        add("config.jade.plugin_confluence.jade_mechanical_component", "Mechanical Info");

        add("creativetab.confluence.building_blocks", "Confluence | Buildings");
        add("creativetab.confluence.natural_blocks", "Confluence | Naturals");
        add("creativetab.confluence.materials", "Confluence | Materials");
        add("creativetab.confluence.tools", "Confluence | Tools");
        add("creativetab.confluence.warriors", "Confluence | Warriors");
        add("creativetab.confluence.rangers", "Confluence | Rangers");
        add("creativetab.confluence.mages", "Confluence | Mages");
        add("creativetab.confluence.summoners", "Confluence | Summoners");
        add("creativetab.confluence.misc", "Confluence | Miscellaneous");
        add("creativetab.confluence.food_and_potions", "Confluence | Food & Potions");
        add("creativetab.confluence.armors", "Confluence | Armors");
        add("creativetab.confluence.accessories", "Confluence | Accessories");
        add("creativetab.confluence.mechanical", "Confluence | Mechanical");

        add("item.confluence.meteorite_ingot.tooltip", "Warm to the touch");
        add("item.confluence.alpha.desc", "C418 - alpha");

        add("curios.tooltip.speed_boots", "The wearer can run super fast");
        add("curios.tooltip.may_fly", "Allows flight");
        add("curios.tooltip.jump_boost", "Increases jump height");
        add("curios.tooltip.multi_jump", "Allows the holder to double jump");
        add("curios.tooltip.fall_resistance", "Increases fall resistance");
        add("curios.tooltip.negates_fall_damage", "Negates fall damage");
        add("curios.tooltip.watch", "Tell the time");
        add("curios.tooltip.fire_immune", "Grants immunity to fire blocks");
        add("curios.tooltip.fluid_walk.part", "Provides the ability to walk on water & honey");
        add("curios.tooltip.fluid_walk.all", "Provides the ability t walk on water, honey & lava");
        add("curios.tooltip.lava_immune", "Provides 7 seconds of immunity to lava");
        add("curios.tooltip.lava_hurt_reduce", "Reduces damage from touching lava");
        add("curios.tooltip.fire_attack", "Melee attacks inflict fire damage");
        add("curios.tooltip.auto_attack", "Enables auto swing for melee weapons");
        add("curios.tooltip.aggro_attach", "Enemies are more likely to target you");
        add("curios.tooltip.armor_pass", "Increases armor penetration by %s");
        add("curios.tooltip.projectile_attack", "%s%% increased ranged damage");
        add("curios.tooltip.compass", "Displays horizontal position");
        add("curios.tooltip.depth_meter", "Displays depth");
        add("curios.tooltip.dps_meter", "Displays your damage per second");
        add("curios.tooltip.fishermans_pocket_guide", "Displays fishing information");
        add("curios.tooltip.life_form_analyzer", "Displays the name of rare creatures around you");
        add("curios.tooltip.metal_detector", "Displays the most valuable ore around you");
        add("curios.tooltip.radar", "Detects enemies around you");
        add("curios.tooltip.sextant", "Displays the phase of the moon");
        add("curios.tooltip.stopwatch", "Displays how fast the player is moving");
        add("curios.tooltip.tally_counter", "Displays how many monsters have been killed");
        add("curios.tooltip.weather_radio", "Displays the weather");
        add("curios.tooltip.scope", "Increases view range for ranged weapons");
        add("curios.tooltip.scope2", "Hold ranged weapon and crouch to zoom out");
        add("curios.tooltip.wall_climb", "Allows the ability to climb walls, hold shift key to slide down");
        add("curios.tooltip.wall_slide", "Allows the ability to slide down walls, hold shift key to slide down quickly");
        add("curios.tooltip.tabi", "Allows the ability to dash while double tap a direction");
        add("curios.tooltip.dodge", "Gives a chance to dodge attacks");

        add("info.confluence.time", "Time: [%s:%s]");
        add("info.confluence.radar", "Enemies: %s");
        add("info.confluence.compass.east", "East: %s, ");
        add("info.confluence.compass.west", "West: %s, ");
        add("info.confluence.compass.south", "South: %s");
        add("info.confluence.compass.north", "North: %s");
        add("info.confluence.depth_meter.surface", "Surface: %s");
        add("info.confluence.depth_meter.underground", "Underground: %s");
        add("info.confluence.tally_counter.unknown", "Kill count unavailable");
        add("info.confluence.tally_counter", "Killed '");
        add("info.confluence.life_form_analyzer.none", "No rare creatures nearby!");
        add("info.confluence.life_form_analyzer", "%s detected nearby!");
        add("info.confluence.metal_detector.none", "No treasure nearby!");
        add("info.confluence.metal_detector", "%s detected nearby!");
        add("info.confluence.stopwatch", "Speed: %s m/s");
        add("info.confluence.dps_meter", "DPS: %s");
        add("info.confluence.sextant.0", "Moon phase: Full Moon");
        add("info.confluence.sextant.1", "Moon phase: Waning Gibbous");
        add("info.confluence.sextant.2", "Moon phase: Third Quarter");
        add("info.confluence.sextant.3", "Moon phase: Waning Crescent");
        add("info.confluence.sextant.4", "Moon phase: New Moon");
        add("info.confluence.sextant.5", "Moon phase: Waxing Crescent");
        add("info.confluence.sextant.6", "Moon phase: First Quarter");
        add("info.confluence.sextant.7", "Moon phase: Waxing Gibbous");
        add("info.confluence.weather_radio.clear", "Weather: Clear, Wind Speed: %s");
        add("info.confluence.weather_radio.cloudy", "Weather: Cloudy, Wind Speed: %s");
        add("info.confluence.weather_radio.rain", "Weather: Rain, Wind Speed: %s");
        add("info.confluence.weather_radio.snow", "Weather: Snow, Wind Speed: %s");
        add("info.confluence.weather_radio.thunder", "Weather: Thunder, Wind Speed: %s");
        add("info.confluence.fishermans_pocket_guide", "Fishing Power: %s");
        add("info.confluence.bait", "Bait Power: %s%%");
        add("info.confluence.network", "#%s Signal: %s");
        add("info.confluence.mobattackmob", "%s Try Attack %s");
        add("info.confluence.choosemob", "Choose %s ...");

        add("key.confluence.hook", "Throwing Hook");
        add("key.confluence.metal_detector", "Detect Metal");
        add("key.confluence.step_stool", "Step Stool");

        add("curios.identifier.hook", "Hook");
        add("curios.identifier.accessory", "Accessory");
        add("curios.modifiers.accessory", "When worn as accessory:");

        add("item.confluence.demon_heart.tooltip", "Permanently increases the number of accessory slots");
        add("item.confluence.adhesive_bandage.tooltip", "Immunity to Bleeding");
        add("item.confluence.medicated_bandage.tooltip", "Immunity to Poison and Bleeding");
        add("item.confluence.armor_bracing.tooltip", "Immunity to Weakness and Broken Armor");
        add("item.confluence.armor_polish.tooltip", "Immunity to Broken Armor");
        add("item.confluence.vitamins.tooltip", "Immunity to Weakness");
        add("item.confluence.the_plan.tooltip", "Immunity to Slow and Confusion");
        add("item.confluence.fast_clock.tooltip", "Immunity to Slow");
        add("item.confluence.trifold_map.tooltip", "Immunity to Confusion");
        add("item.confluence.countercurse_mantra.tooltip", "Immunity to Silence and Curse");
        add("item.confluence.megaphone.tooltip", "Immunity to Silence");
        add("item.confluence.nazar.tooltip", "Immunity to Curse");
        add("item.confluence.reflective_shades.tooltip", "Immunity to Blindness and Petrification");
        add("item.confluence.blindfold.tooltip", "Immunity to Blindness");
        add("item.confluence.pocket_mirror.tooltip", "Immunity to Petrification");
        add("item.confluence.ankh_charm.tooltip", "Grants immunity to most debuffs");
        add("item.confluence.ankh_shield.tooltip", "Grants immunity to most debuffs");
        add("item.confluence.honey_comb.tooltip", "Releases bees and douses the user in honey when damaged");
        add("item.confluence.bezoar.tooltip", "Immunity to Poison");
        add("item.confluence.cobalt_shield.tooltip", "Grants immunity to knockback");
        add("item.confluence.band_of_regeneration.tooltip", "Slowly regenerates life");
        add("item.confluence.band_of_starpower.tooltip", "Increases maximum mana by 20");
        add("item.confluence.mechanical_lens.tooltip", "Grants improved wire vision");
        add("item.confluence.spectre_goggles.tooltip", "Enables Echo Sight, showing hidden blocks");
        add("item.confluence.magiluminescence.tooltip", "Increases movement speed and acceleration");
        add("item.confluence.magiluminescence.tooltip2", "Provides light when worn");
        add("item.confluence.magiluminescence.tooltip3", "'A brief light in my dark life.'");
        add("item.confluence.sandstorm_on_a_bottle.tooltip", "Allows the holder to do an improved double jump");
        add("item.confluence.ice_skates.tooltip", "Provides extra mobility on ice");
        add("item.confluence.ice_skates.tooltip2", "Ice will not break when you fall on it");
        add("item.confluence.dunerider_boots.tooltip", "The wearer can run super fast, and even faster on sand");
        add("item.confluence.dunerider_boots.tooltip2", "'Walk without rhythm and you won't attract the worm'");
        add("item.confluence.lucky_horseshoe.tooltip", "'Said to bring good fortune and keep evil spirits at bay'");
        add("item.confluence.lightning_boots.tooltip", "Allows flight, super fast running");
        add("item.confluence.horseshoe_balloon.tooltip", "Increases jump height and negates fall damage");
        add("item.confluence.lava_waders.tooltip2", "Grants immunity to fire blocks and 7 seconds of immunity to lava");
        add("item.confluence.bundle_of_balloons.tooltip", "Allows the holder to quadruple jump");
        add("item.confluence.bundle_of_horseshoe_balloon.tooltip", "Allows the holder to quadruple jump");
        add("item.confluence.bundle_of_horseshoe_balloon.tooltip2", "Increases jump height and negates fall damage");
        add("item.confluence.water_walking_boots.tooltip", "Provides the ability to walk on water & honey");
        add("item.confluence.magma_skull.tooltip", "Immunity to fire blocks, melee attacks deal fire damage");
        add("item.confluence.frostspark_boots.tooltip", "Allows flight, super fast running, and extra mobility on ice");
        add("item.confluence.sun_stone.tooltip", "During daytime, grants minor increase");
        add("item.confluence.moon_stone.tooltip", "During nighttime, grants minor increase");
        add("item.confluence.putrid_scent.tooltip", "Enemies are less likely to target you");
        add("item.confluence.panic_necklace.tooltip", "Increases movement speed after taking damage");
        add("item.confluence.paladins_shield.tooltip", "Absorbs 25% of damage done to players on your team when above 25% life");
        add("item.confluence.frozen_shield.tooltip", "Absorbs 25% of damage done to players on your team when above 25% life");
        add("item.confluence.frozen_shield.tooltip2", "Puts a shell around the owner when below 50% life that reduces damage by 25%");
        add("item.confluence.frozen_turtle_shell.tooltip", "Puts a shell around the owner when below 50% life that reduces damage by 25%");
        add("item.confluence.fire_gauntlet.tooltip", "Increases melee knockback and melee attacks inflict fire damage");
        add("item.confluence.cross_necklace.tooltip", "Increases TOTAL_LENGTH of invincibility after taking damage");
        add("item.confluence.terraspark_boots.tooltip2", "Grants immunity to fire blocks and 7 seconds of immunity to lava");
        add("item.confluence.fledgling_wings.tooltip", "Allows flight and slow fall");
        add("item.confluence.worm_scarf.tooltip", "Reduces damage taken by 17%");
        add("item.confluence.shield_of_cthulhu.tooltip", "Allows the player to dash into the enemy, sprinting to dsh");
        add("item.confluence.brain_of_confusion.tooltip", "Has a chance to create illusions and dodge an attack");
        add("item.confluence.brain_of_confusion.tooltip2", "Temporarily increase critical chance after dodge");
        add("item.confluence.brain_of_confusion.tooltip3", "May confuse nearby enemies after being struck");
        add("item.confluence.royal_gel.tooltip", "Slimes cannot damage you");
        add("item.confluence.magic_cuffs.tooltip", "Maximum mana is increased by 20");
        add("item.confluence.magic_cuffs.tooltip2", "Restores mana when injured");
        add("item.confluence.magnet_flower.tooltip", "8% reduced mana cost");
        add("item.confluence.magnet_flower.tooltip2", "Automatically uses mana potions when needed");
        add("item.confluence.magnet_flower.tooltip3", "Increases the pickup range of Mana Stars");
        add("item.confluence.mana_flower.tooltip", "8% reduced mana cost");
        add("item.confluence.mana_flower.tooltip2", "Automatically uses mana potions when needed");
        add("item.confluence.arcane_flower.tooltip", "8% reduced mana cost");
        add("item.confluence.arcane_flower.tooltip2", "Automatically uses mana potions when needed");
        add("item.confluence.arcane_flower.tooltip3", "The enemy is unlikely to target you");
        add("item.confluence.celestial_cuffs.tooltip", "Increases the pickup range of Mana Stars");
        add("item.confluence.celestial_cuffs.tooltip2", "Restores mana when injured");
        add("item.confluence.celestial_cuffs.tooltip3", "Maximum mana is increased by 20");
        add("item.confluence.celestial_magnet.tooltip", "Increases the pickup range of Mana Stars");
        add("item.confluence.celestial_emblem.tooltip", "Increases the pickup range of Mana Stars");
        add("item.confluence.celestial_emblem.tooltip2", "15% increased magic damage");
        add("item.confluence.celestial_stone.tooltip", "Slightly increases the attribute value");
        add("item.confluence.charm_of_myths.tooltip", "Provides health regeneration and reduces the cooldown of healing potions");
        add("item.confluence.philosophers_stone.tooltip", "Reduced the cooldown of Healing Potions");
        add("item.confluence.mana_regeneration_band.tooltip", "Maximum mana is increased by 20");
        add("item.confluence.mana_regeneration_band.tooltip2", "Increases mana regeneration rate");
        add("item.confluence.natures_gift.tooltip", "6% reduced mana cost");
        add("item.confluence.gold_ring.tooltip", "Expanded coin pickup");
        add("item.confluence.gravity_globe.tooltip", "Allows the holder to reverse gravity");
        add("item.confluence.gravity_globe.tooltip2", "Press Jump to change gravity");
        add("item.confluence.sweetheart_necklace.tooltip", "When damaged, the bee is released and the user is immersed in honey and increases movement speed");
        add("item.confluence.ancient_chisel.tooltip2", "“Age-old problems require age-old solutions”");
        add("item.confluence.lucky_coin.tooltip", "Hitting an enemy can sometimes drop extra coins");
        add("item.confluence.coin_ring.tooltip", "Increasing the coin pickup range and hitting enemies will sometimes drop additional coins");
        add("item.confluence.hive_pack.tooltip", "Increases the strength of friendly bees");
        add("item.confluence.treasure_magnet.tooltip", "Expanded item pickup");
        add("item.confluence.flower_boots.tooltip", "Flowers grow on the grass you walk on");
        add("item.confluence.high_test_fishing_line.tooltip", "Line never breaks");
        add("item.confluence.angler_earring.tooltip", "Increases fishing power");
        add("item.confluence.fishing_bobber.tooltip", "Increases fishing power");
        add("item.confluence.glowing_fishing_bobber.tooltip", "Increases fishing power,Your bobber now glows");
        add("item.confluence.lava_moss_fishing_bobber.tooltip", "Increases fishing power,Your bobber now glows");
        add("item.confluence.helium_moss_fishing_bobber.tooltip", "Increases fishing power,Your bobber now glows");
        add("item.confluence.neon_moss_fishing_bobber.tooltip", "Increases fishing power,Your bobber now glows");
        add("item.confluence.argon_moss_fishing_bobber.tooltip", "Increases fishing power,Your bobber now glows");
        add("item.confluence.krypton_moss_fishing_bobber.tooltip", "Increases fishing power,Your bobber now glows");
        add("item.confluence.xenon_moss_fishing_bobber.tooltip", "Increases fishing power,Your bobber now glows");
        add("item.confluence.tackle_box.tooltip", "−5% bait consumption chance");
        add("item.confluence.angler_tackle_bag.tooltip", "Line never breaks and −5% bait consumption chance");
        add("item.confluence.lavaproof_fishing_hook.tooltip", "Allows fishing in lava regardless of bait or rod used.");
        add("item.confluence.lavaproof_tackle_bag.tooltip1", "Allows fishing in lava regardless of bait or rod used.");
        add("item.confluence.lavaproof_tackle_bag.tooltip2", "Line never breaks and −5% bait consumption chance");
        add("item.confluence.hand_warmer.tooltip", "Provides immunity to chill and freezing effects");
        add("item.confluence.mana_cloak.tooltip", "Stars restore mana when collected");
        add("item.confluence.star_cloak.tooltip", "Causes stars to fall after taking damage");
        add("item.confluence.magic_quiver.tooltip2", "20% chance to not consume arrows");
        add("item.confluence.molten_quiver.tooltip", "Lights wooden arrows ablaze");
        add("item.confluence.molten_quiver.tooltip2", "'Quiver in fear!'");
        add("item.confluence.recon_scope.tooltip", "'Enemy spotted'");
        add("item.confluence.portable_cement_mixer.tooltip", "Decreased 'Right Click Delay' by 1");
        add("item.confluence.brick_layer.tooltip", "Decreased 'Right Click Delay' by 1");
        add("item.confluence.architect_gizmo_pack.tooltip", "Decreased 'Right Click Delay' by 2, cannot stack the decrease of its materials");
        add("item.confluence.climbing_claws.tooltip", "Improved ability if combined with Shoe Spikes");
        add("item.confluence.shoe_spikes.tooltip", "Improved ability if combined with Climbing Claws");
        add("item.confluence.frog_gear.tooltip", "'It ain't easy being green'");
        add("item.confluence.hand_of_creation.tooltip2", "Decreased 'Right Click Delay' by 3, cannot stack the decrease of its material");
        add("item.confluence.hand_of_creation.tooltip3", "Increases pickup range for items");
        add("item.confluence.step_stool.tooltip", "Press ↑ key to stand higher, and press Shift key to down");
        add("item.confluence.step_stool.tooltip2", "Extra Step: %s");

        add("item.confluence.magic_conch.pos", "Pos: [%s, %s, %s]");

        add("death.attack.falling_star", "%1$s was squashed by a falling star");
        add("death.attack.boulder", "%1$s  is crushed by boulder");

        add("painting.confluence.magic_harp.title", "MAGIC_HARP");
        add("painting.confluence.magic_harp.author", "BiliBili_魔法竖琴waaa，看上去傻傻的...");
        add("painting.confluence.westernat.title", "WESTERNAT");
        add("painting.confluence.westernat.author", "BiliBili_Westernat233，MC21世纪以来，最具有印象派主义的白桦树绘画!");
        add("painting.confluence.cooobrid.title", "COOOBRID");
        add("painting.confluence.cooobrid.author", "BiliBili_事一只一只一只鸽子，事一只只会咕咕咕的鸽子");
        add("painting.confluence.nakinosi.title", "NAKINOSI");
        add("painting.confluence.nakinosi.author", "BiliBili_咕咕咕的屑枕头，世界上最好看的渐变头发！");
        add("painting.confluence.maker.title", "MAKER");
        add("painting.confluence.maker.author", "BiliBili_Maker-2333，是Maker不是Marker！");
        add("painting.confluence.mustard_oasis.title", "MUSTARD_OASIS");
        add("painting.confluence.mustard_oasis.author", "BiliBili_芥末Oasis，芥末配fish，豪赤😋");
        add("painting.confluence.a_pigeon_delight.title", "A_PIGEON_DELIGHT");
        add("painting.confluence.a_pigeon_delight.author", "BiliBili_一只鸽子悦");
        add("painting.confluence.sheep_mink.title", "SHEEP_MINK");
        add("painting.confluence.sheep_mink.author", "BiliBili_眠羊敏克，“啊？我打json？”");
        add("painting.confluence.voila.title", "VOILA");
        add("painting.confluence.voila.author", "BiliBili_风起下片灬");
        add("painting.confluence.xuanyu_1725.title", "XUANYU");
        add("painting.confluence.xuanyu_1725.author", "BiliBili_轩宇1725");
        add("painting.confluence.shadow_end.title", "SHADOW_END");
        add("painting.confluence.shadow_end.author", "BiliBili_影末子");
        add("painting.confluence.kl_jiana.title", "KL_JIANA");
        add("painting.confluence.kl_jiana.author", "BiliBili_KL_JIANA");
        add("painting.confluence.hunao.title", "HUNAO");
        add("painting.confluence.hunao.author", "BiliBili_小胡闹鸭");
        add("painting.confluence.sihuai_2412.title", "SIHUAI_2412");
        add("painting.confluence.sihuai_2412.author", "BiliBili_思怀_2412");


        add("advancements.start.title", "Old World, New Journey!");
        add("advancements.start.descr", "The afterlife of convergence and exchange");
        add("advancements.mana_star.title", "Gather the power of the stars");
        add("advancements.mana_star.descr", "The stars will increase your magical powers");
        add("advancements.tin_ingot.title", "resonant harmony, reminiscent of bronze");
        add("advancements.tin_ingot.descr", "Acquire tin ingot, more exotic minerals blend into the world");
        add("advancements.meteorite_ingot.title", "Something extraterrestrial");
        add("advancements.meteorite_ingot.descr", "Acquire meteorite ingot");
        add("advancements.platinum_ingot.title", "Precious metals");
        add("advancements.platinum_ingot.descr", "Acquire platinum ingot");
        add("advancements.ebony_ingot.title", "Corrupt will");
        add("advancements.ebony_ingot.descr", "Acquire ebony ingot");
        add("advancements.tr_crimson_ingot.title", "Crimson flesh");
        add("advancements.tr_crimson_ingot.descr", "Acquire crimson ingot");
        add("advancements.pretty_in_pink.title", "pretty_in_pink");
        add("advancements.pretty_in_pink.descr", "Find the rare pink slime and defeat it");


        add("prefix.confluence.quick", "Quick");
        add("prefix.confluence.hasty", "Hasty");
        add("prefix.confluence.deadly", "Deadly");

        add("prefix.confluence.tooltip.plus", "+%s%% %s");
        add("prefix.confluence.tooltip.take", "-%s%% %s");
        add("prefix.confluence.tooltip.add", "+%s %s");
        add("prefix.confluence.tooltip.attack_damage", "Attack Damage");
        add("prefix.confluence.tooltip.attack_speed", "Attack Speed");
        add("prefix.confluence.tooltip.critical_chance", "Critical Chance");
        add("prefix.confluence.tooltip.knock_back", "Knock Back");
        add("prefix.confluence.tooltip.velocity", "Velocity");
        add("prefix.confluence.tooltip.mana_cost", "Mana Cost");
        add("prefix.confluence.tooltip.armor", "Armor");
        add("prefix.confluence.tooltip.additional_mana", "Additional Mana");
        add("prefix.confluence.tooltip.movement_speed", "Movement Speed");

        add("fluid_type.confluence.shimmer", "Shimmer");
        add("fluid_type.confluence.honey", "Honey");

        add("title.confluence.shimmer_transmutation", "Shimmer Transmutation");
        add("condition.confluence.shimmer_transmutation", "Required game phase: %s");

        add("item.confluence.aglet.info", "It can be found in surface Chests, Wooden Crates and Pearlwood Crates.");
        add("item.confluence.amber_horseshoe_balloon.info", "It can be crafted at a Tinkerer's Workshop with a Lucky Horseshoe and a Honey Balloon.");
        add("item.confluence.amber_horseshoe_balloon.info2", "On the Desktop version Desktop version, Console version Console version, and Mobile version Mobile version, it also grants the Honey buff after being damaged.");
        add("item.confluence.amphibian_boots.info", "The Amphibian Boots are crafted by combining the Sailfish Boots and Frog Leg at a Tinkerer's Workshop. It provides the benefits of both.");
        add("item.confluence.anklet_of_the_wind.info", "The effect also stacks with the movement speed bonus of the Aglet.");
        add("item.confluence.anklet_of_the_wind.info2", "It can be found in Jungle and Bramble Crates.");
        add("item.confluence.balloon_pufferfish.info", "It can be obtained via fishing in any biome.");
        add("item.confluence.blizzard_in_a_bottle.info", "The Blizard in a Bottle has a chance of being found inside Frozen Chests in the Ice biome, as well as chance of being obtained from Frozen and Boreal Crates.");
        add("item.confluence.cloud_in_a_bottle.info", "It can be found in Gold Chests in the Underground and Cavern layers.");
        add("item.confluence.dunerider_boots.info", "The Dunerider Boots has a chance of being found in Sandstone Chests in the Underground Desert and a chance of being found in Oasis Crates and Mirage Crates obtained from fishing in the Oasis.");
        add("item.confluence.fledgling_wings.info", "The Fledgling Wings can be obtained from Skyware Chests on Floating Islands, as well as Sky Crates and Azure Crates from fishing.");
        add("item.confluence.flippers.info", "It can be found in Water Chests and Ocean/Seaside Crates.");
        add("item.confluence.flurry_boots.info", "It can be found in Frozen Chests in the underground Snow Biome, as well as Boreal Crates.");
        add("item.confluence.frog_leg.info", "The Frog Leg is that can be fished in any viable body of water.");
        add("item.confluence.hand_warmer.info", "It is obtained from Presents.");
        add("item.confluence.hermes_boots.info", "Hermes Boots are that can be found in Chests in the Underground and Cavern layers.");
        add("item.confluence.ice_skates.info", "Ice Skates have a chance of being found inside Frozen Chests in the Ice biome, as well as chance of being obtained from Boreal Crates.");
        add("item.confluence.lava_charm.info", "It can only be found in Chests in the lower portion of the Caverns where lava pools can naturally spawn, as opposed to Chests throughout the entirety of the Caverns.");
        add("item.confluence.lucky_horseshoe.info", "The Lucky Horseshoe has a chance found inside Skyware Chests on Floating Islands, as well as chance of being obtained from Sky Crates and Azure Crates.");
        add("item.confluence.sailfish_boots.info", "This item is obtained from Wooden Crates and Iron Crates.");
        add("item.confluence.sandstorm_in_a_bottle.info", "The Sandstorm in a Bottle is found inside Gold Chests within Pyramids.");
        add("item.confluence.shoe_spike.info", "It can be found in Chests in the Underground and Cavern layers.");
        add("item.confluence.step_stool.info", "It can be obtained from wooden box and in a chest on the surface.");;
        add("item.confluence.tsunami_in_a_bottle.info", "The Tsunami in a Bottle is which can be found in Wooden, Iron, Pearlwood, and Mythril Crates.");
        add("item.confluence.water_walking_boots.info", "Water Walking Boots have a chance of being obtained from Water Chests, Ocean Crates, and Seaside Crates.");
        add("item.confluence.compass.info", "It can be");
        add("item.confluence.depth_meter.info", "It can be");
        add("item.confluence.dps_meter.info", "It can be");
        add("item.confluence.fishermans_pocket_guide.info", "The Fisherman's Pocket Guide have chance as a reward for completing the fisherman's fishing quests.");
        add("item.confluence.fish_finder.info", "The Fish Finder have chance as a reward for completing the fisherman's fishing quests.");
        add("item.confluence.mechanical_lens.info", "The Mechanical Lens by purchased from the mechanic villager.");
        add("item.confluence.metal_detector.info", "It can be");
        add("item.confluence.radar.info", "It can be");
        add("item.confluence.sextant.info", "The Sextant have chance as a reward for completing the fisherman's fishing quests.");
        add("item.confluence.tally_counter.info", "It can be");
        add("item.confluence.weather_radio.info", "The Weather Radio have chance as a reward for completing the fisherman's fishing quests.");
        add("item.confluence.arcane_flower.info", "The Arcane Flower is a Hardmode accessory which combines the functionality of the Mana Flower and the aggro-reducing effect of the Putrid Scent.");
        add("item.confluence.band_of_regeneration.info", "The Band of Regeneration is that can be found in Gold Chests in the Underground and Cavern biomes and in Living Mahogany Trees in the Underground Jungle.");
        add("item.confluence.band_of_regeneration.info2", "When equipped, it regenerates 1 health every second.");
        add("item.confluence.band_of_regeneration.info3", "This effect stacks with the player's natural health regeneration, but unlike the natural regeneration, does not slow or stop when the player is moving or being attacked.");
        add("item.confluence.band_of_starpower.info", "The Band of Starpower is that increases the player's maximum mana by 20.");
        add("item.confluence.band_of_starpower.info2", "The Band of Starpower has a 1/5 (20%) chance of being obtained from destroying Shadow Orbs found in the Corruption or a 1/5 (20%) chance from Corrupt Crates and Defiled Crates, which are fished in the Corruption.");
        add("item.confluence.celestial_cuffs.info", "The Celestial Cuffs are a pre-Hardmode accessory which restores mana when the wearer is damaged and increases pickup range for Stars.");
        add("item.confluence.celestial_cuffs.info2", "It also increases maximum mana by 20.");
        add("item.confluence.celestial_cuffs.info3", "Mana restored is equal to the damage of the attack before factoring defense and damage reduction effects.");
        add("item.confluence.celestial_cuffs.info4", "Damage from drowning and debuffs does not trigger this effect, while fall damage will.");
        add("item.confluence.celestial_cuffs.info5", "This effect does not stack with the mana restoration effect of the Magic Cuffs.");
        add("item.confluence.celestial_cuffs.info6", "The mana star pickup range is increased by 18.75 tiles, for a total of 21.375 tiles.");
        add("item.confluence.celestial_cuffs.info7", "This effect does not stack with the pickup range increase effect of the Celestial Magnet, Magnet Flower or Celestial Emblem.");
        add("item.confluence.celestial_emblem.info", "The Celestial Emblem is a Hardmode accessory that offers 15% increased magic damage and a 18.75-tile increased pickup range for Stars (21.375 tile total range).");
        add("item.confluence.celestial_magnet.info", "The Celestial Magnet is that greatly increases the pickup range for Stars.");
        add("item.confluence.celestial_magnet.info2", "The increase in pickup range is 18.75 tiles, extending the base range of 2.625 tiles to 21.375 tiles.");
        add("item.confluence.celestial_magnet.info3", "This effect does not stack with that of any of the Celestial Magnet's upgrades.");
        add("item.confluence.celestial_magnet.info4", "The Celestial Magnet has a 1/4 (25%) of being found inside Skyware Chests on Floating Islands, as well as a 1/4 (25%) chance of being obtained from Sky Crates and Azure Crates.");
        add("item.confluence.charm_of_myths.info", "The Charm of Myths is a Hardmode accessory which combines the effects of Band of Regeneration and Philosopher's Stone.");
        add("item.confluence.charm_of_myths.info2", "When equipped, it regenerates 1 health every second and decreases the Potion Sickness debuff duration by 25%.");
        add("item.confluence.charm_of_myths.info3", "Therefore, 45 seconds after consuming a recovery potion while the Charm of Myths is equipped, another one can be consumed.");
        add("item.confluence.magic_cuffs.info", "The Magic Cuffs are a pre-Hardmode accessory which increases maximum mana by 20 and restores mana when the wearer is damaged.");
        add("item.confluence.magic_cuffs.info2", "Mana restored is equal to the damage of the attack before factoring defense and damage reduction effects.");
        add("item.confluence.magic_cuffs.info3", "Damage from drowning and debuffs does not trigger this effect, while damage from falling will.");
        add("item.confluence.magic_cuffs.info4", "This effect does not stack with the mana restoration effect of the Celestial Cuffs.");
        add("item.confluence.magnet_flower.info", "The Magnet Flower is that reduces mana usage by 8%, automatically uses Mana Potions when needed, and increases pickup range for Stars by 18.75 tiles.");
        add("item.confluence.magnet_flower.info2", "It will use the first available Mana Potion in the player's inventory when out of mana (from left to right and top to bottom).");
        add("item.confluence.magnet_flower.info3", "The Magnet Flower has the exact same functional effects of both its component items.");
        add("item.confluence.mana_cloak.info", "The Mana Cloak is a Hardmode accessory that combines the effects of the Mana Flower and Star Cloak. It also adds a new effect to the stars spawned by the Star Cloak.");
        add("item.confluence.mana_cloak.info2", "It also adds a new effect to the stars spawned by the Star Cloak.");
        add("item.confluence.mana_cloak.info3", "When the player takes damage, the Mana Cloak will spawn three stars that damage enemies.");
        add("item.confluence.mana_cloak.info4", "The mana star will disappear 5 seconds after it is spawned if not picked up.");
        add("item.confluence.mana_cloak.info5", "Note that only one mana-restoring star can spawn per second, no matter how many times the Mana Cloak is triggered.");
        add("item.confluence.mana_flower.info", "The Mana Flower is a pre-Hardmode accessory that reduces mana usage by 8%, and enables auto-consumption of any mana-restoring potions in the player's inventory when mana is depleted.");
        add("item.confluence.mana_flower.info2", "The Mana Flower stacks with other mana cost-reduction items, including Nature's Gift. It is crafted at the Tinkerer's Workshop.");
        add("item.confluence.mana_regeneration_band.info", "The Mana Regeneration Band is item made by combining a Band of Starpower and a Band of Regeneration at a Tinkerer's Workshop.");
        add("item.confluence.mana_regeneration_band.info2", "It somewhat combines the effects of both bands, increasing a player's maximum mana and converting the bonus health regeneration provided by the Band of Regeneration into mana regeneration.");
        add("item.confluence.natures_gift.info", "Nature's Gift is that reduces the mana cost of using magic weapons and other mana-consuming items by 6%.");
        add("item.confluence.natures_gift.info2", "It is acquired by harvesting a rare flower that grows on Jungle grass in the Underground Jungle, using any weapon or tool. The flower appears as a blue version of the Jungle Rose.");
        add("item.confluence.philosophers_stone.info", "The Philosopher's Stone is a Hardmode accessory which decreases the Potion Sickness debuff duration by 25%.");
        add("item.confluence.philosophers_stone.info2", "Therefore, 45 seconds after consuming a recovery potion while the Philosopher's Stone is equipped, another one can be consumed.");
        add("item.confluence.philosophers_stone.info3", "It has a 1/6 (16.67%) / 1/7 (14.29%) chance to be dropped by Mimics.");
        add("item.confluence.adhesive_bandage.info", "The Adhesive Bandage is an immunity accessory that grants the player immunity to the Bleeding debuff. It has a 1/100 (1%) / 1/50 (2%) chance to drop from Rusty Armored Bones, Werewolves, and Angler Fish.");
        add("item.confluence.adhesive_bandage.info2", "It is one of the ingredients required to make the Medicated Bandage, which is a crafting material required to make the Ankh Charm, further required to make the Ankh Shield.");
        add("item.confluence.ankh_charm.info", "The Ankh Charm is a Hardmode immunity accessory which combines the effects of the Armor Bracing, Medicated Bandage, The Plan, Countercurse Mantra, and Reflective Shades.");
        add("item.confluence.ankh_shield.info", "The Ankh Shield is a Hardmode shield and immunity accessory which provides immunity to 12, knockback immunity, and an additional 4 defense.");
        add("item.confluence.ankh_shield.info2", "It is crafted from an Obsidian Shield and an Ankh Charm at the Tinkerer's Workshop.");
        add("item.confluence.armor_bracing.info", "Armor Bracing is a Hardmode immunity accessory that combines the functions of the Vitamins and the Armor Polish.");
        add("item.confluence.armor_bracing.info2", "This item provides immunity from the Weak and Broken Armor debuffs.");
        add("item.confluence.armor_bracing.info3", "It is one of the ingredients required to make the Ankh Charm, which is further required to make the Ankh Shield.");
        add("item.confluence.armor_polish.info", "The Armor Polish is a Hardmode immunity accessory that grants the player immunity to the Broken Armor debuff.");
        add("item.confluence.armor_polish.info2", "It has a 1/100 (1%) / 199/10000 (1.99%) chance to drop from Armored Skeletons and Blue Armored Bones.");
        add("item.confluence.armor_polish.info3", "It is one of the ingredients required to make the Armor Bracing, which is a crafting material required to make the Ankh Charm, further required to make the Ankh Shield.");
        add("item.confluence.avenger_emblem.info", "The Avenger Emblem is a Hardmode accessory that grants 12% increased damage to all weapons.");
        add("item.confluence.bee_cloak.info", "The Bee Cloak is a Hardmode accessory that combines the effects of the Star Cloak and the Honey Comb.");
        add("item.confluence.bee_cloak.info2", "When the player is injured, three stars will fall on the player's current location and bees are released.");
        add("item.confluence.berserkers_glove.info", "The Berserker's Glove is a Hardmode accessory crafted from the Power Glove and Flesh Knuckles, granting the abilities of both.");
        add("item.confluence.bezoar.info", "The Bezoar is an immunity accessory that grants the player immunity to the Poisoned debuff.");
        add("item.confluence.bezoar.info2", "It has a 1/100 (1%) / 1/50 (2%) chance to drop from Hornets, Moss Hornets, and Toxic Sludges.");
        add("item.confluence.bezoar.info3", "It is one of the ingredients required to make the Medicated Bandage, which is a crafting material required to make the Ankh Charm, further required to make the Ankh Shield.");
        add("item.confluence.black_belt.info", "The Black Belt is a Hardmode, post-Plantera accessory that grants a 10% chance to dodge an attack, including instances of damage taken from hazards such as traps and lava.");
        add("item.confluence.black_belt.info2", "A cloud of smoke surrounds the player upon a successful dodge.");
        add("item.confluence.black_belt.info3", "The Black Belt has a 1/12 (8.33%) / 23/144 (15.97%) chance to drop from Bone Lees in the post-Plantera Dungeon.");
        add("item.confluence.blindfold.info", "The Blindfold is a Hardmode immunity accessory that grants the player immunity to the Darkness debuff.");
        add("item.confluence.blindfold.info2", "It has a 1/100 (1%) / 1/50 (2%) chance to drop from Corrupt Slimes, Slimelings, Crimslimes, Dark Mummies, and Blood Mummies.");
        add("item.confluence.blindfold.info3", "It is one of the ingredients required to make the Reflective Shades, which are a crafting material required to make the Ankh Charm, further required to make the Ankh Shield.");
        add("item.confluence.celestial_stone.info", "The Celestial Stone is a Hardmode post-Golem accessory crafted from a Moon Stone and a Sun Stone at the Tinkerer's Workshop.");
        add("item.confluence.celestial_stone.info2", "It offers the same boosts as its components do, and as such, it is active during both day and night.");
        add("item.confluence.celestial_stone.info3", "It can be combined with the Moon Shell to form a Celestial Shell。");
        add("item.confluence.celestial_stone.info4", "Stat boosts:");
        add("item.confluence.celestial_stone.info5", "+%s%% melee speed");
        add("item.confluence.celestial_stone.info6", "+%s%% damage (all types)");
        add("item.confluence.celestial_stone.info7", "+%s%% critical strike chance");
        add("item.confluence.celestial_stone.info8", "+1 HP/s life regeneration");
        add("item.confluence.celestial_stone.info9", "+%s defense");
        add("item.confluence.celestial_stone.info10", "+15% mining speed");
        add("item.confluence.celestial_stone.info11", "+0.5 minion knockback");
        add("item.confluence.cobalt_shield.info", "The Cobalt Shield is a pre-Hardmode shield accessory that grants the player immunity to knockback when equipped, and also provides 1 defense.");
        add("item.confluence.cobalt_shield.info2", "The Cobalt Shield has a 1/7 (14.29%) chance of being obtained from the Locked Gold Chests found in the Dungeon, as well as a 1/7 (14.29%) chance of being obtained from Golden Lock Boxes.");
        add("item.confluence.countercurse_mantra.info", "The Countercurse Mantra is an immunity accessory that combines the functions of the Megaphone and the Nazar.");
        add("item.confluence.countercurse_mantra.info2", "This item grants immunity to both the Silenced and Cursed debuffs.");
        add("item.confluence.countercurse_mantra.info3", "It is one of the ingredients required to make the Ankh Charm, which is further required to make the Ankh Shield.");
        add("item.confluence.cross_necklace.info", "The Cross Necklace is a Hardmode accessory that doubles the duration of the invincibility a player is afforded after taking damage, from about 0.67 seconds to about 1.33 seconds.");
        add("item.confluence.cross_necklace.info2", "The Cross Necklace has a 1/6 (16.67%) chance to be dropped by Mimics.");
        add("item.confluence.destroyer_emblem.info", "The Destroyer Emblem is a Hardmode, post-Golem accessory that gives the player 10% increased damage and 8% increased critical strike chance.");
        add("item.confluence.eye_of_the_golem.info", "The Eye of the Golem is a Hardmode, post-Golem accessory that grants +10% critical strike chance.");
        add("item.confluence.eye_of_the_golem.info2", "It has a 1/7 (14.29%) chance of being dropped by Golem.");
        add("item.confluence.fast_clock.info", "The Fast Clock is a Hardmode immunity accessory that grants the player immunity to the Slow debuff.");
        add("item.confluence.fast_clock.info2", "It has a 1/100 (1%) / 1/50 (2%) chance to drop from Pixies, Mummies, and Wraiths.");
        add("item.confluence.fast_clock.info3", "It is one of the ingredients required to make The Plan, which is a crafting material required to make the Ankh Charm, further required to make the Ankh Shield.");
        add("item.confluence.feral_claws.info", "Feral Claws are that increases melee attack speed by 12%, and stacks with all other attack speed boosts.");
        add("item.confluence.feral_claws.info2", "Feral Claws can be found in Jungle Crates, Bramble Crates, and Ivy Chests located in Jungle Shrines and at the base of a Living Mahogany Tree in the Underground Jungle.");
        add("item.confluence.feral_claws.info3", "In addition to increasing melee attack speed, Feral Claws give autoswing to all melee weapons and Whips.");
        add("item.confluence.fire_gauntlet.info", "The Fire Gauntlet is a Hardmode accessory that boosts melee weapons in the following ways:");
        add("item.confluence.fire_gauntlet.info2", "Both the weapon sprite and projectile emit orange light particles that gives off light");
        add("item.confluence.fire_gauntlet.info3", "They cause the Hellfire debuff (does not apply in PvP)");
        add("item.confluence.fire_gauntlet.info4", "+100% knockback");
        add("item.confluence.fire_gauntlet.info5", "+12% damage");
        add("item.confluence.fire_gauntlet.info6", "+12% attack speed");
        add("item.confluence.fire_gauntlet.info7", "They gain autoswing (also applies to whips)");
        add("item.confluence.fire_gauntlet.info8", "+10% size on some melee weapons");
        add("item.confluence.fire_gauntlet.info9", "The Fire Gauntlet is only available after defeating all three mechanical bosses.");
        add("item.confluence.flesh_knuckles.info", "Flesh Knuckles are a Hardmode accessory. They increase the player's defense by 8 and aggro by 400.");
        add("item.confluence.flesh_knuckles.info2", "Flesh Knuckles have a 1/5 (20%) chance to be dropped by Crimson Mimics.");
        add("item.confluence.frozen_shield.info", "The Frozen Shield is a Hardmode, post-Plantera shield accessory that combines the functionalities of the Paladin's Shield and the Frozen Turtle Shell:");
        add("item.confluence.frozen_shield.info2", "It redirects some damage done to teammates to the player, increases defense by 6, grants immunity to knockback, and provides the player with a damage-absorbing shield when they are at low health.");
        add("item.confluence.frozen_turtle_shell.info", "The Frozen Turtle Shell is a Hardmode accessory that grants the Ice Barrier buff when equipped,");
        add("item.confluence.frozen_turtle_shell.info2", "Gives 25% damage reduction as long as their health remains at or below 50%.");
        add("item.confluence.frozen_turtle_shell.info3", "The Frozen Turtle Shell has a 1/50 (2%) chance of being dropped by Ice Tortoises in the Ice biome.");
        add("item.confluence.hero_shield.info", "The Hero Shield is a Hardmode post-Plantera shield accessory that redirects 25% of damage from players on the same team while above 25% health, similar to the effect of the Paladin's Shield.");
        add("item.confluence.hero_shield.info2", "Furthermore, it increases defense by 10, increases aggro by 400, and grants immunity to knockback.");
        add("item.confluence.honey_comb.info", "The Honey Comb is a pre-Hardmode accessory which, when equipped, spawns 1–3 (or 1–4 with a Hive Pack equipped) bee projectiles which attack nearby enemies each time the player takes damage.");
        add("item.confluence.honey_comb.info2", "It also grants the Honey buff for 5 seconds after being damaged.");
        add("item.confluence.honey_comb.info3", "The Honey Comb has a 1/3 (33.33%) chance to be dropped by the Queen Bee.");
        add("item.confluence.magma_stone.info", "The Magma Stone is that drops from Lava Bats (2% chance) and Hellbats (0.67% chance) in The Underworld.");
        add("item.confluence.magma_stone.info2", "It causes the wearer's melee attacks to inflict the Hellfire debuff on enemies, and also add orange flame particles effect on both the weapon sprite and their projectile that gives off light.");
        add("item.confluence.magma_stone.info3", "The duration of the debuff is random, and varies according to the table on the right.");
        add("item.confluence.mechanical_glove.info", "The Mechanical Glove is a Hardmode accessory that doubles all melee weapons' knockback, and increases melee damage and speed by 12%.");
        add("item.confluence.mechanical_glove.info2", "It is only available after defeating all mechanical bosses.");
        add("item.confluence.mechanical_glove.info3", "The Mechanical Glove enables autoswing for all melee weapons and whips and increases their size by 10%.");
        add("item.confluence.medicated_bandage.info", "The Medicated Bandage is an immunity accessory that combines the functions of the Adhesive Bandage and the Bezoar.");
        add("item.confluence.medicated_bandage.info2", "This item grants immunity to any Bleeding and Poison debuffs.");
        add("item.confluence.medicated_bandage.info3", "It is one of the ingredients required to make the Ankh Charm, which is further required to make the Ankh Shield.");
        add("item.confluence.megaphone.info", "The Megaphone is an immunity accessory that grants the player immunity to the Silenced debuff.");
        add("item.confluence.megaphone.info2", "It has a 1/100 (1%) / 1/50 (2%) chance to drop from Pixies, Green Jellyfish, Dark Mummies, and Blood Mummies.");
        add("item.confluence.megaphone.info3", "It is one of the ingredients required to make the Countercurse Mantra, which is a crafting material required to make the Ankh Charm, further required to make the Ankh Shield.");
        add("item.confluence.molten_skull_rose.info", "The Molten Skull Rose is that represents the final upgrade of the Obsidian Skull.");
        add("item.confluence.molten_skull_rose.info2", "It grants 7 seconds of immunity to lava, immunity from fire blocks, and reduces damage taken from lava.");
        add("item.confluence.molten_skull_rose.info3", "When worn, the item can be seen on the players head.");
        add("item.confluence.molten_skull_rose.info4", "This item can also be crafted in three different ways.");
        add("item.confluence.moon_stone.info", "The Moon Stone is a Hardmode accessory which has a 1/35 (2.86%) / 69/1225 (5.63%) chance to drop from Vampires during the Solar Eclipse event.");
        add("item.confluence.moon_stone.info2", "It grants the same stat bonuses as the Sun Stone, but these bonuses will only activate during the night or during a Solar Eclipse.");
        add("item.confluence.moon_stone.info3", "The stat bonuses are:");
        add("item.confluence.moon_stone.info4", "+10% melee speed");
        add("item.confluence.moon_stone.info5", "+10% damage (all types)");
        add("item.confluence.moon_stone.info6", "+2% critical strike chance");
        add("item.confluence.moon_stone.info7", "+1 HP/s health regeneration");
        add("item.confluence.moon_stone.info8", "+4 defense");
        add("item.confluence.moon_stone.info9", "+15% mining speed");
        add("item.confluence.moon_stone.info10", "+0.5 minion knockback");
        add("item.confluence.nazar.info", "The Nazar is a post-Skeletron immunity accessory that grants the player immunity to the Cursed debuff.");
        add("item.confluence.nazar.info2", "It has a 1/100 (1%) / 1/50 (2%) chance to drop from Cursed Skulls, Giant Cursed Skulls, Cursed Hammers, Crimson Axes, and Enchanted Swords.");
        add("item.confluence.nazar.info3", "It is one of the ingredients of the Countercurse Mantra, which is a crafting material required to make the Ankh Charm, which can be further crafted into the Ankh Shield.");
        add("item.confluence.obsidian_rose.info", "The Obsidian Rose is that reduces the base damage taken from lava from 80 to 35 and halves the duration of the On Fire! debuff inflicted by it from 7 / 14 / 17.5 seconds to 3.5 / 7 / 8.75 seconds.");
        add("item.confluence.obsidian_rose.info2", "It has a 1/20 (5%) chance of being dropped by Fire Imps, an enemy found in The Underworld.");
        add("item.confluence.obsidian_shield.info", "The Obsidian Shield is a shield accessory made from the Cobalt Shield and Obsidian Skull, and combines their functionality as well as their defense boosts.");
        add("item.confluence.obsidian_shield.info2", "It grants immunity from knockback, as well as immunity from the Burning debuff, and provides 2 defense.");
        add("item.confluence.obsidian_skull.info", "The Obsidian Skull is an immunity accessory that grants immunity to the Burning debuff normally inflicted by contact with Meteorite, Hellstone, and Hellstone Bricks.");
        add("item.confluence.obsidian_skull.info2", "It does not grant immunity to lava or other fire-based attacks. It additionally provides 1 defense.");
        add("item.confluence.obsidian_skull.info3", "Meteorite and Hellstone can be mined without Obsidian protection, as the player only takes damage when touching them in their placed block form; they can be mined from a distance without this immunity.");
        add("item.confluence.obsidian_skull.info4", "However, this item makes the process much easier.");
        add("item.confluence.obsidian_skull_rose.info", "The Obsidian Skull Rose is crafted from the Obsidian Skull and Obsidian Rose that combines their functionality, granting immunity to fire blocks and reduced damage from lava.");
        add("item.confluence.obsidian_skull_rose.info2", "The Obsidian Skull Rose can be worn in a Social Accessory Slot as a vanity item.");
        add("item.confluence.paladins_shield.info", "The Paladin's Shield is a Hardmode, post-Plantera shield accessory that functions primarily in multiplayer. While equipped, and when the wearer's health is above 25%, it grants all nearby players on their team the Paladin's Shield buff:");
        add("item.confluence.paladins_shield.info2", "This buff causes 25% of any damage inflicted on them to transfer to the wearer of the shield instead. In both singleplayer and multiplayer, the Paladin's Shield also provides the wearer immunity to knockback (like the Cobalt Shield and its variants), and provides an additional 6 defense.");
        add("item.confluence.paladins_shield.info3", "The Paladin's Shield has a 1/10 (10%) / 19/100 (19%) chance of being dropped by Paladins in the post-Plantera Dungeon.");
        add("item.confluence.panic_necklace.info", "The Panic Necklace is, that, when equipped, grants the player the Panic! buff for 8 seconds when harmed by any source of damage besides fire blocks, increasing movement speed by 100%.");
        add("item.confluence.panic_necklace.info2", "The Panic Necklace has a 1/5 (20%) chance of being obtained from destroying Crimson Hearts found in the Crimson or a 1/5 (20%) chance from Crimson Crates and Hematic Crates, which are fished in the Crimson.");
        add("item.confluence.pocket_mirror.info", "The Pocket Mirror is a Hardmode immunity accessory that grants the player immunity to the Stoned debuff.");
        add("item.confluence.pocket_mirror.info2", "It has a 1/40 (2.5%) / 1/20 (5%) chance of being dropped by Medusas.");
        add("item.confluence.pocket_mirror.info3", "It is one of the ingredients required to make the Reflective Shades, which are a crafting material required to make the Ankh Charm, further required to make the Ankh Shield.");
        add("item.confluence.power_glove.info", "The Power Glove is a Hardmode accessory that doubles melee knockback and adds 12% increased melee speed.");
        add("item.confluence.power_glove.info2", "It simply combines the effects of Feral Claws and Titan Glove with no benefits lost.");
        add("item.confluence.power_glove.info3", "Additionally, the Power Glove enables autoswing on all melee weapons and whips and increases the size of all melee weapons by 10%.");
        add("item.confluence.putrid_scent.info", "The Putrid Scent is a Hardmode accessory which increases damage and critical strike chance by 5% and decreases aggro by 400.");
        add("item.confluence.putrid_scent.info2", "It has a 1/5 (20%) chance to be dropped by Corrupt Mimics.");
        add("item.confluence.putrid_scent.info3", "It is unrelated to the Stinky debuff.");
        add("item.confluence.ranger_emblem.info", "The Ranger Emblem is a Hardmode accessory that increases ranged damage by 15%. It has a 1/4 (25%) chance to drop from the Wall of Flesh.");
        add("item.confluence.reflective_shades.info", "The Reflective Shades are a Hardmode immunity accessory which combines the functions of the Blindfold and the Pocket Mirror, granting immunity to the Darkness and Stoned debuffs.");
        add("item.confluence.reflective_shades.info2", "They are one of the ingredients required to make the Ankh Charm, which is further required to make the Ankh Shield.");
        add("item.confluence.shackle.info", "The Shackle is that grants 1 point of defense. It is dropped by most kinds of Zombies with a 1/50 (2%) chance.");
        add("item.confluence.shackle.info2", "Shackles may be useful early in the game when only few accessories are available.");
        add("item.confluence.shackle.info3", "Typically, they should be replaced with more valuable accessories once out of free slots.");
        add("item.confluence.shark_tooth_necklace.info", "The Shark Tooth Necklace is which has a 1/149 (0.67%) / 1/75 (1.33%) chance to drop from Blood Zombies and Dripplers found during a Blood Moon.");
        add("item.confluence.shark_tooth_necklace.info2", "It increases the player's armor penetration by 5 when equipped.");
        add("item.confluence.sorcerer_emblem.info", "The Sorcerer Emblem is a Hardmode accessory that increases magic damage by 15%. It has a 1/4 (25%) chance to drop from the Wall of Flesh.");
        add("item.confluence.star_cloak.info", "The Star Cloak is a Hardmode accessory that causes three stars to fall around the player whenever the player takes damage. It consumes no mana.");
        add("item.confluence.star_cloak.info2", "The stars pass through blocks until reaching the player's altitude, at which point they continue falling until hitting blocks.");
        add("item.confluence.star_cloak.info3", "They pierce through an unlimited number of enemies.");
        add("item.confluence.star_cloak.info4", "The Star Cloak has a 1/6 (16.67%) chance to be dropped by Mimics.");
        add("item.confluence.star_cloak.info5", "The stars deal 75 / 150 / 225 damage which is not classified as any of the four damage types and therefore cannot be modified by any buffs or equipment. Furthermore, the stars have 25 armor penetration.");
        add("item.confluence.star_veil.info", "The Star Veil is a Hardmode accessory that combines the functions of the Star Cloak and the Cross Necklace, spawning falling star projectiles and increasing the TOTAL_LENGTH of the invincibility frames granted when the player is hurt.");
        add("item.confluence.stinger_necklace.info", "The Stinger Necklace is a pre-Hardmode accessory that is obtainable after defeating the Queen Bee.");
        add("item.confluence.stinger_necklace.info2", "This item combines the Shark Tooth Necklace and the Honey Comb accessories, giving the player 5 armor penetration as well as releasing 1–3 / 1–4 bees when the wearer takes damage and granting the Honey buff for 5 seconds.");
        add("item.confluence.sun_stone.info", "The Sun Stone is a Hardmode, post-Golem accessory which has a 1/7 (14.29%) chance of being dropped by Golem.");
        add("item.confluence.sun_stone.info2", "It grants the same stat bonuses as the Moon Stone;");
        add("item.confluence.sun_stone.info3", "however, these bonuses only activate during the day.");
        add("item.confluence.the_plan.info", "The Plan is a Hardmode immunity accessory which combines the functions of the Fast Clock and the Trifold Map, granting immunity to the Slow and Confusion debuffs.");
        add("item.confluence.the_plan.info2", "It is one of the ingredients required to make the Ankh Charm, which is further required to make the Ankh Shield.");
        add("item.confluence.titan_glove.info", "The Titan Glove is a Hardmode accessory that doubles player-inflicted melee knockback.");
        add("item.confluence.titan_glove.info2", "The Titan Glove has a 1/6 (16.67%) chance of being dropped by Mimics.");
        add("item.confluence.titan_glove.info3", "It increases the size of melee weapons by 10%.");
        add("item.confluence.trifold_map.info", "The Trifold Map is a Hardmode immunity accessory that grants the player immunity to the Confused debuff.");
        add("item.confluence.trifold_map.info2", "It has a 1/100 (1%) / 1/50 (2%) chance to drop from Clowns, Giant Bats, Light Mummies.");
        add("item.confluence.trifold_map.info3", "It is one of the ingredients required to craft The Plan, which is a crafting material required to make the Ankh Charm, further required to make the Ankh Shield.");
        add("item.confluence.vitamins.info", "Vitamins are a Hardmode immunity accessory that grants the player immunity to the Weak debuff.");
        add("item.confluence.vitamins.info2", "It has a 1/100 (1%) / 1/50 (2%) chance to drop from Corruptors and Floaty Grosses.");
        add("item.confluence.vitamins.info3", "Vitamins are one of the ingredients required to make the Armor Bracing, which is a crafting material required to make the Ankh Charm, further required to make the Ankh Shield.");
        add("item.confluence.warrior_emblem.info", "The Warrior Emblem is a Hardmode accessory that increases melee damage by 15%. It has a 1/4 (25%) chance to drop from the Wall of Flesh.");
        add("item.confluence.ancient_chisel.info", "The Ancient Chisel is that increases mining speed by 25%, similarly to a Mining Potion. It can be found in Sandstone Chests in the Underground Desert and in Oasis Crates or Mirage Crates.");
        add("item.confluence.extendo_grip.info", "The Extendo Grip is that extends block mining and placement reach by 3 tiles horizontally and 2 tiles vertically. ");
        add("item.confluence.angler_earring.info", "The Angler Earring is that increases the player's current Fishing Power by 10 when equipped.");
        add("item.confluence.angler_tackle_bag.info", "The Angler Tackle Bag is that combines the functionality of its components:");
        add("item.confluence.angler_tackle_bag.info2", "The Angler Earring's 10% boost to Fishing power, the Tackle Box's chance to not consume bait, and the unbreakable quality of the High Test Fishing Line.");
        add("item.confluence.angler_tackle_bag.info3", "The Angler Tackle Bag's increase in fishing power stacks with that of the Angler Earring and Lavaproof Tackle Bag, granting a total boost of 30% if all three are equipped.");
        add("item.confluence.angler_tackle_bag.info4", "The decreased chance to consume bait does not stack with that of the Tackle Box or the Lavaproof Tackle Bag.");
        add("item.confluence.fishing_bobber.info", "Fishing Bobbers are accessories that change the appearance of a fishing pole's bobber and increase the player's Fishing Power by 10.");
        add("item.confluence.high_test_fishing_line.info", "The High Test Fishing Line is that prevents fishing line from breaking while fishing when equipped.");
        add("item.confluence.high_test_fishing_line.info2", "Without the High Test Fishing Line equipped, there is a 1/7 (14.29%) chance that the line will break on any reel-in that was supposed to yield a catch.");
        add("item.confluence.lavaproof_fishing_hook.info", "The Lavaproof Fishing Hook is that can be found in Obsidian Crates and Hellstone Crates, both of which can be obtained from fishing in lava.");
        add("item.confluence.lavaproof_fishing_hook.info2", "When equipped, it allows the player to catch fish in lava with any bait and any fishing pole.");
        add("item.confluence.lavaproof_tackle_bag.info", "The Lavaproof Tackle Bag is that combines the functionalities of its components:");
        add("item.confluence.lavaproof_tackle_bag.info2", "The Angler Earring's 10% boost to fishing power, the Tackle Box's chance not to consume bait, the unbreakable quality of the High Test Fishing Line, and the ability to fish in lava from the Lavaproof Fishing Hook.");
        add("item.confluence.lavaproof_tackle_bag.info3", "The Lavaproof Tackle Bag's increase in fishing power stacks with that of the Angler Earring and the Angler Tackle Bag, granting a total boost of 30% if all three are equipped.");
        add("item.confluence.lavaproof_tackle_bag.info4", "The decreased chance to consume bait does not stack with that of the Tackle Box or the Angler Tackle Bag.");
        add("item.confluence.tackle_box.info", "The Tackle Box is that decreases the chance of bait consumption while fishing.");
        add("item.confluence.flower_boots.info", "Flower Boots can occasionally be found in Ivy Chests, Jungle Crates and Bramble Crates.");
        add("item.confluence.gold_ring.info", "The Gold Ring has chance to.");
        add("item.confluence.lucky_coin.info", "The Lucky Coin has chance to.");
        add("item.confluence.spectre_goggles.info", "The Spectre Goggles.");
        add("item.confluence.treasure_magnet.info", "The Treasure Magnet has chance to.");
        add("item.confluence.brain_of_confusion.info", "The Brain of Confusion is a pre-Hardmode accessory that, upon taking damage while equipped, nearby enemies have a 3/5 (60%) chance of receiving the Confused debuff for at minimum 1.5 seconds.");
        add("item.confluence.brain_of_confusion.info2", "The chance, duration, and area of effect of the debuff are based on the amount of damage taken.");
        add("item.confluence.brain_of_confusion.info3", "Furthermore, the player wielding it has a 1/6 (16.67%) chance of dodging an attack, which inflicts the Cerebral Mindtrick debuff on them for four seconds.");
        add("item.confluence.brain_of_confusion.info4", "Despite being a debuff, it increases critical strike chance and summon damage by 10%.");
        add("item.confluence.brain_of_confusion.info5", "While the debuff is active, the player cannot dodge another attack.");
        add("item.confluence.brain_of_confusion.info6", "The Brain of Confusion is always dropped from the Brain of Cthulhu's Treasure Bag in Expert Mode.");
        add("item.confluence.gravity_globe.info", "The Gravity Globe is a Hardmode, post-Moon Lord accessory that allows the holder to flip gravity, so that the player falls up instead of down, and toggle gravity back to normal afterward. Once equipped, pressing the Up key toggles the gravity direction.");
        add("item.confluence.gravity_globe.info2", "This only affects the player with the item equipped. The Gravity Globe is always dropped from the Moon Lord's Treasure Bag in Expert Mode.");
        add("item.confluence.hive_pack.info", "The Hive Pack is a pre-Hardmode accessory that, when equipped, grants a 1/2 (50%) chance of replacing friendly Bee projectiles with larger \"Giant Bees\".");
        add("item.confluence.hive_pack.info2", "The Hive Pack is always dropped from the Queen Bee's Treasure Bag in Expert Mode.");
        add("item.confluence.royal_gel.info", "The Royal Gel is a pre-Hardmode accessory that pacifies most slimes when equipped, causing them to no longer pursue the player, and will deal no contact damage or fire projectiles, even if the player deals damage to them.");
        add("item.confluence.royal_gel.info2", "The Royal Gel is always dropped from King Slime's Treasure Bag in Expert Mode.");
        add("item.confluence.royal_gel.info3", "This does not apply to the following slimes:");
        add("item.confluence.royal_gel.info4", "King Slime and his Spiked Slimes, though the normal Blue Slimes that King Slime spawns remain docile.");
        add("item.confluence.royal_gel.info5", "Queen Slime and her Bouncy Slimes, Crystal Slimes, and Heavenly Slimes.");
        add("item.confluence.shield_of_cthulhu.info", "The Shield of Cthulhu is a pre-Hardmode shield accessory that allows the player to perform a dash attack by double-tapping either the Left or Right key.");
        add("item.confluence.shield_of_cthulhu.info2", "Dashing into an enemy deals 30 damage, recoils the player backward, and grants 0.07 seconds of invincibility frames.");
        add("item.confluence.shield_of_cthulhu.info3", "The Shield of Cthulhu is always dropped from the Eye of Cthulhu's Treasure Bag in Expert Mode.");
        add("item.confluence.worm_scarf.info", "The Worm Scarf is a pre-Hardmode accessory that reduces incoming damage by 17%.");
        add("item.confluence.worm_scarf.info2", "This damage reduction from this item is calculated after defense is applied.");
        add("item.confluence.worm_scarf.info3", "The Worm Scarf is always dropped from the Eater of Worlds' Treasure Bag in Expert Mode.");

        add("block.confluence.timers_block_1_1", "1 Second Timer");
        add("block.confluence.timers_block_3_1", "3 Second Timer");
        add("block.confluence.timers_block_5_1", "5 Second TImer");
        add("block.confluence.timers_block_1_2", "1/2 Second Timer");
        add("block.confluence.timers_block_1_4", "1/4 Second TImer");
        add("block.confluence.base_chest_block.locked_golden", "Locked Golden Chest");
        add("block.confluence.base_chest_block.unlocked_golden", "Golden Chest");
        add("block.confluence.base_chest_block.death_golden", "Death Golden Chest");
        add("block.confluence.base_chest_block.locked_shadow", "Locked Shadow Chest");
        add("block.confluence.base_chest_block.unlocked_shadow", "Shadow Chest");
        add("block.confluence.base_chest_block.death_shadow", "Death Shadow Chest");
        add("block.confluence.base_chest_block.unlocked_lvy", "Lvy Chest");
        add("block.confluence.base_chest_block.death_lvy", "Death Lvy Chest");
        add("block.confluence.base_chest_block.unlocked_frozen", "Frozen Chest");
        add("block.confluence.base_chest_block.death_frozen", "Death Frozen Chest");
        add("block.confluence.base_chest_block.unlocked_water", "Water Chest");
        add("block.confluence.base_chest_block.death_water", "Death Water Chest");
        add("block.confluence.base_chest_block.unlocked_skyware", "Skyware Chest");
        add("block.confluence.base_chest_block.death_skyware", "Death Skyware Chest");

        add("resourcepack.terraria_art", "Terraria Art");
        add("resourcepack.mainstream_connected_ores", "Mainstream Connected Ores");
        add("resourcepack.ter_armor", "Mainstream Terraria Armor Textures");

        add("event.confluence.blood_moon", "The Blood Moon is rising...");

        add("attribute.name.generic.critical_chance", "Critical Chance");
        add("attribute.name.generic.ranged_velocity", "Ranged Velocity");
        add("attribute.name.generic.ranged_damage", "Ranged Damage");
        add("attribute.name.generic.dodge_chance", "Dodge Chance");
        add("attribute.name.generic.mining_speed", "Mining Speed");
        add("attribute.name.generic.aggro", "Aggro");
        add("attribute.name.generic.magic_damage", "Magic Damage");
        add("attribute.name.generic.armor_pass", "Armor Pass");
        add("attribute.name.generic.pickup_range", "Pickup Range");

        add("entity.minecraft.villager.confluence.sky_miller", "Sky Miller");

        add("container.confluence.workshop", "Workshop");
        add("title.confluence.workshop", "Workshop");

        add("achievements.confluence.boots_of_the_hero.title", "Boots of the Hero");
        add("achievements.confluence.boots_of_the_hero.description", "Forged from the finest boots of fire and ice.");
        add("achievements.confluence.black_mirror.title", "Black Mirror");
        add("achievements.confluence.black_mirror.description", "You'll never leave home without it again.");
        add("achievements.confluence.ankhumulation_complete.title", "Ankhumulation Complete");
        add("achievements.confluence.ankhumulation_complete.description", "The finest protection from unpleasant maladies and ailments.");

        ModBlocks.BLOCKS.getEntries().forEach(block -> {
            Block block1 = block.get();
            if (block1 instanceof WallSignBlock || block1 instanceof WallTorchBlock) return;
            if (block1 instanceof CustomName customName) {
                if (customName.getGenName() != null) {
                    add(block1, customName.getGenName());
                }
            } else {
                add(block1, toTitleCase(block.getId().getPath()));
            }
        });
        ModItems.ITEMS.getEntries().forEach(item -> {
            Item item1 = item.get();
            if (item1 instanceof BlockItem) return;
            if (item1 instanceof CustomName customName) {
                if (customName.getGenName() != null) {
                    add(item1, customName.getGenName());
                }
            } else {
                add(item1, toTitleCase(item.getId().getPath()));
            }
        });
        ModEntities.ENTITIES.getEntries().forEach(entity -> add(entity.get(), toTitleCase(entity.getId().getPath())));
        ModEffects.EFFECTS.getEntries().forEach(effect -> add(effect.get(), toTitleCase(effect.getId().getPath())));
        for (ModPrefix.Universal universal : ModPrefix.Universal.values()) {
            add("prefix.confluence." + universal.name().toLowerCase(), toTitleCase(universal.name()));
        }
        for (ModPrefix.Common common : ModPrefix.Common.values()) {
            if (common == ModPrefix.Common.QUICK || common == ModPrefix.Common.DEADLY) continue;
            add("prefix.confluence." + common.name().toLowerCase(), toTitleCase(common.name()));
        }
        for (ModPrefix.Melee melee : ModPrefix.Melee.values()) {
            add("prefix.confluence." + melee.name().toLowerCase(), toTitleCase(melee.name()));
        }
        for (ModPrefix.Ranged ranged : ModPrefix.Ranged.values()) {
            if (ranged == ModPrefix.Ranged.HASTY || ranged == ModPrefix.Ranged.DEADLY) continue;
            add("prefix.confluence." + ranged.name().toLowerCase(), toTitleCase(ranged.name()));
        }
        for (ModPrefix.Magic magicAndSumming : ModPrefix.Magic.values()) {
            add("prefix.confluence." + magicAndSumming.name().toLowerCase(), toTitleCase(magicAndSumming.name()));
        }
        for (ModPrefix.Curio curio : ModPrefix.Curio.values()) {
            if (curio == ModPrefix.Curio.HASTY || curio == ModPrefix.Curio.QUICK) continue;
            add("prefix.confluence." + curio.name().toLowerCase(), toTitleCase(curio.name()));
        }
    }
}
