package org.confluence.mod.datagen;

import net.minecraft.data.PackOutput;
import net.minecraft.world.item.Item;
import net.minecraftforge.common.data.LanguageProvider;
import org.confluence.mod.Confluence;
import org.confluence.mod.datagen.limit.CustomName;
import org.confluence.mod.effect.ModEffects;
import org.confluence.mod.entity.ModEntities;
import org.confluence.mod.item.ModItems;

import java.util.Arrays;
import java.util.stream.Collectors;

public class ModEnglishProvider extends LanguageProvider {
    public ModEnglishProvider(PackOutput output) {
        super(output, Confluence.MODID, "en_us");
    }

    @Override
    protected void addTranslations() {
        add("creativetab.confluence.accessories", "Confluence | Accessories");

        add("curios.tooltip.speed_boots", "The wearer can run super fast");
        add("curios.tooltip.may_fly", "Allows flight");
        add("curios.tooltip.jump_boost", "Increases jump height");
        add("curios.tooltip.multi_jump", "Allows the holder to double jump");
        add("curios.tooltip.fall_resistance", "Increases fall resistance");
        add("curios.tooltip.negates_fall_damage", "Negates fall damage");
        add("curios.tooltip.watch", "Tell the time");
        add("curios.tooltip.fire_immune", "Grants immunity to fire blocks");
        add("curios.tooltip.fluid_walk.part", "Provides the ability to walk on water & honey");
        add("curios.tooltip.fluid_walk.all", "Provides the ability t walk on water, honey & lava");
        add("curios.tooltip.lava_immune", "Provides 7 seconds of immunity to lava");
        add("curios.tooltip.lava_hurt_reduce", "Reduces damage from touching lava");
        add("curios.tooltip.fire_attack", "Melee attacks inflict fire damage");
        add("curios.tooltip.auto_attack", "Enables auto swing for melee weapons");
        add("curios.tooltip.aggro_attach", "Enemies are more likely to target you");
        add("curios.tooltip.armor_pass", "Increases armor penetration by %s");
        add("curios.tooltip.compass", "Displays horizontal position");
        add("curios.tooltip.depth_meter", "Displays depth");
        add("curios.tooltip.dps_meter", "Displays your damage per second");
        add("curios.tooltip.fishermans_pocket_guide", "Displays fishing information");
        add("curios.tooltip.life_form_analyzer", "Displays the name of rare creatures around you");
        add("curios.tooltip.metal_detector", "Displays the most valuable ore around you");
        add("curios.tooltip.radar", "Detects enemies around you");
        add("curios.tooltip.sextant", "Displays the phase of the moon");
        add("curios.tooltip.stopwatch", "Displays how fast the player is moving");
        add("curios.tooltip.tally_counter", "Displays how many monsters have been killed");
        add("curios.tooltip.weather_radio", "Displays the weather");
        add("curios.tooltip.scope", "Increases view range for ranged weapons");
        add("curios.tooltip.scope2", "Hold ranged weapon and crouch to zoom out");
        add("curios.tooltip.wall_climb", "Allows the ability to climb walls, hold shift key to slide down");
        add("curios.tooltip.wall_slide", "Allows the ability to slide down walls, hold shift key to slide down quickly");
        add("curios.tooltip.tabi", "Allows the ability to dash while double tap a direction");
        add("curios.tooltip.dodge", "Gives a chance to dodge attacks");

        add("info.confluence.time", "Time: [%s:%s]");
        add("info.confluence.radar", "Enemies: %s");
        add("info.confluence.compass.east", "East: %s, ");
        add("info.confluence.compass.west", "West: %s, ");
        add("info.confluence.compass.south", "South: %s");
        add("info.confluence.compass.north", "North: %s");
        add("info.confluence.depth_meter.surface", "Surface: %s");
        add("info.confluence.depth_meter.underground", "Underground: %s");
        add("info.confluence.tally_counter.unknown", "Kill count unavailable");
        add("info.confluence.tally_counter", "Killed '");
        add("info.confluence.life_form_analyzer.none", "No rare creatures nearby!");
        add("info.confluence.life_form_analyzer", "%s detected nearby!");
        add("info.confluence.metal_detector.none", "No treasure nearby!");
        add("info.confluence.metal_detector", "%s detected nearby!");
        add("info.confluence.stopwatch", "Speed: %s m/s");
        add("info.confluence.dps_meter", "DPS: %s");
        add("info.confluence.sextant.0", "Moon phase: Full Moon");
        add("info.confluence.sextant.1", "Moon phase: Waning Gibbous");
        add("info.confluence.sextant.2", "Moon phase: Third Quarter");
        add("info.confluence.sextant.3", "Moon phase: Waning Crescent");
        add("info.confluence.sextant.4", "Moon phase: New Moon");
        add("info.confluence.sextant.5", "Moon phase: Waxing Crescent");
        add("info.confluence.sextant.6", "Moon phase: First Quarter");
        add("info.confluence.sextant.7", "Moon phase: Waxing Gibbous");
        add("info.confluence.weather_radio.clear", "Weather: Clear");
        add("info.confluence.weather_radio.cloudy", "Weather: Cloudy");
        add("info.confluence.weather_radio.rain", "Weather: Rain");
        add("info.confluence.weather_radio.snow", "Weather: Snow");
        add("info.confluence.weather_radio.thunder", "Weather: Thunder");
        add("info.confluence.fishermans_pocket_guide", "Fishing Power: %s");

        add("key.confluence.metal_detector", "Detect Metal");
        add("key.confluence.step_stool", "Step Stool");

        add("curios.identifier.accessory", "Accessory");
        add("curios.modifiers.accessory", "When worn as accessory:");

        add("item.confluence.demon_heart.tooltip", "Permanently increases the number of accessory slots");
        add("item.confluence.vitamins.tooltip", "Immunity to Weakness");
        add("item.confluence.fast_clock.tooltip", "Immunity to Slow");
        add("item.confluence.blindfold.tooltip", "Immunity to Blindness");
        add("item.confluence.bezoar.tooltip", "Immunity to Poison");
        add("item.confluence.trifold_map.tooltip", "Immunity to Nausea");
        add("item.confluence.the_plan.tooltip", "Immunity to Slow and Nausea");
        add("item.confluence.holy_water.tooltip", "Immunity to Wither");
        add("item.confluence.energy_bar.tooltip", "Immunity to Hunger");
        add("item.confluence.flashlight.tooltip", "Immunity to Darkness");
        add("item.confluence.hand_drill.tooltip", "Immunity to Mining Fatigue");
        add("item.confluence.shot_put.tooltip", "Immunity to Levitation");
        add("item.confluence.searchlight.tooltip", "Immunity to Blindness and Darkness");
        add("item.confluence.detoxification_capsule.tooltip", "Immunity to Poison and Wither");
        add("item.confluence.explorers_equipment.tooltip", "Immunity to Mining Fatigue and Levitation");
        add("item.confluence.nutrient_solution.tooltip", "Immunity to Weakness and Hunger");
        add("item.confluence.ankh_charm.tooltip", "Grants immunity to most debuffs");
        add("item.confluence.cobalt_shield.tooltip", "Grants immunity to knockback");
        add("item.confluence.band_of_regeneration.tooltip", "Slowly regenerates life");
        add("item.confluence.mechanical_lens.tooltip", "Grants improved wire vision");
        add("item.confluence.spectre_goggles.tooltip", "Enables Echo Sight, showing hidden blocks");
        add("item.confluence.magiluminescence.tooltip", "Increases movement speed and acceleration");
        add("item.confluence.magiluminescence.tooltip3", "'A brief light in my dark life.'");
        add("item.confluence.sandstorm_on_a_bottle.tooltip", "Allows the holder to do an improved double jump");
        add("item.confluence.ice_skates.tooltip", "Provides extra mobility on ice");
        add("item.confluence.dunerider_boots.tooltip", "The wearer can run super fast, and even faster on sand");
        add("item.confluence.dunerider_boots.tooltip2", "'Walk without rhythm and you won't attract the worm'");
        add("item.confluence.lucky_horseshoe.tooltip", "'Said to bring good fortune and keep evil spirits at bay'");
        add("item.confluence.lightning_boots.tooltip", "Allows flight, super fast running");
        add("item.confluence.horseshoe_balloon.tooltip", "Increases jump height and negates fall damage");
        add("item.confluence.lava_waders.tooltip2", "Grants immunity to fire blocks and 7 seconds of immunity to lava");
        add("item.confluence.bundle_of_balloons.tooltip", "Allows the holder to quadruple jump");
        add("item.confluence.bundle_of_horseshoe_balloon.tooltip", "Allows the holder to quadruple jump");
        add("item.confluence.bundle_of_horseshoe_balloon.tooltip2", "Increases jump height and negates fall damage");
        add("item.confluence.water_walking_boots.tooltip", "Provides the ability to walk on water & honey");
        add("item.confluence.magma_skull.tooltip", "Immunity to fire blocks, melee attacks deal fire damage");
        add("item.confluence.frostspark_boots.tooltip", "Allows flight, super fast running, and extra mobility on ice");
        add("item.confluence.sun_stone.tooltip", "During daytime, grants minor increase");
        add("item.confluence.moon_stone.tooltip", "During nighttime, grants minor increase");
        add("item.confluence.putrid_scent.tooltip", "Enemies are less likely to target you");
        add("item.confluence.panic_necklace.tooltip", "Increases movement speed after taking damage");
        add("item.confluence.paladins_shield.tooltip", "Absorbs 25% of damage done to players on your team when above 25% life");
        add("item.confluence.frozen_shield.tooltip", "Absorbs 25% of damage done to players on your team when above 25% life");
        add("item.confluence.frozen_shield.tooltip2", "Puts a shell around the owner when below 50% life that reduces damage by 25%");
        add("item.confluence.frozen_turtle_shell.tooltip", "Puts a shell around the owner when below 50% life that reduces damage by 25%");
        add("item.confluence.fire_gauntlet.tooltip", "Increases melee knockback and melee attacks inflict fire damage");
        add("item.confluence.cross_necklace.tooltip", "Increases length of invincibility after taking damage");
        add("item.confluence.terraspark_boots.tooltip2", "Grants immunity to fire blocks and 7 seconds of immunity to lava");
        add("item.confluence.fledgling_wings.tooltip", "Allows flight and slow fall");
        add("item.confluence.worm_scarf.tooltip", "Reduces damage taken by 17%");
        add("item.confluence.shield_of_cthulhu.tooltip", "Allows the player to dash into the enemy, sprinting to dsh");
        add("item.confluence.brain_of_confusion.tooltip", "Has a chance to create illusions and dodge an attack");
        add("item.confluence.brain_of_confusion.tooltip2", "Temporarily increase critical chance after dodge");
        add("item.confluence.brain_of_confusion.tooltip3", "May confuse nearby enemies after being struck");
        add("item.confluence.royal_gel.tooltip", "Slimes become friendly");
        add("item.confluence.arcane_flower.tooltip3", "The enemy is unlikely to target you");
        add("item.confluence.celestial_stone.tooltip", "Slightly increases the attribute value");
        add("item.confluence.charm_of_myths.tooltip", "Provides health regeneration and reduces the cooldown of healing potions");
        add("item.confluence.philosophers_stone.tooltip", "Reduced the cooldown of Healing Potions");
        add("item.confluence.gold_ring.tooltip", "Expanded coin pickup");
        add("item.confluence.gravity_globe.tooltip", "Allows the holder to reverse gravity");
        add("item.confluence.gravity_globe.tooltip2", "Press Jump to change gravity");
        add("item.confluence.ancient_chisel.tooltip2", "“Age-old problems require age-old solutions”");
        add("item.confluence.treasure_magnet.tooltip", "Expanded item pickup");
        add("item.confluence.flower_boots.tooltip", "Flowers grow on the grass you walk on");
        add("item.confluence.hand_warmer.tooltip", "Provides immunity to chill and freezing effects");
        add("item.confluence.star_cloak.tooltip", "Causes stars to fall after taking damage");
        add("item.confluence.honey_comb.tooltip", "Releases bees and douses the user in honey when damaged");
        add("item.confluence.sweetheart_necklace.tooltip", "When damaged, the bee is released and the user is immersed in honey and increases movement speed");
        add("item.confluence.hive_pack.tooltip", "Increases the strength of friendly bees");
        add("item.confluence.magic_quiver.tooltip2", "20% chance to not consume arrows");
        add("item.confluence.molten_quiver.tooltip", "Lights wooden arrows ablaze");
        add("item.confluence.molten_quiver.tooltip2", "'Quiver in fear!'");
        add("item.confluence.recon_scope.tooltip", "'Enemy spotted'");
        add("item.confluence.portable_cement_mixer.tooltip", "Decreased 'Right Click Delay' by 1");
        add("item.confluence.brick_layer.tooltip", "Decreased 'Right Click Delay' by 1");
        add("item.confluence.architect_gizmo_pack.tooltip", "Decreased 'Right Click Delay' by 2, cannot stack the decrease of its materials");
        add("item.confluence.climbing_claws.tooltip", "Improved ability if combined with Shoe Spikes");
        add("item.confluence.shoe_spikes.tooltip", "Improved ability if combined with Climbing Claws");
        add("item.confluence.frog_gear.tooltip", "'It ain't easy being green'");
        add("item.confluence.hand_of_creation.tooltip2", "Decreased 'Right Click Delay' by 3, cannot stack the decrease of its material");
        add("item.confluence.step_stool.tooltip", "Press ↑ key to stand higher, and press Shift key to down");
        add("item.confluence.step_stool.tooltip2", "Extra Step: %s");
        add("item.confluence.magic_mirror.tooltip", "Gaze in the mirror to return home");
        add("item.confluence.cell_phone.tooltip", "Displays everything");
        add("item.confluence.cell_phone.tooltip2", "Allows you to return home at will");

        add("item.confluence.aglet.info", "It can be found in Shipwreck Chests.");
        add("item.confluence.anklet_of_the_wind.info", "The effect also stacks with the movement speed bonus of the Aglet.");
        add("item.confluence.climbing_claws.info", "It have a Chance to be dropped from Spider.");
        add("item.confluence.cloud_in_a_bottle.info", "It can be found in Chests in the Mineshaft and Dungeon.");
        add("item.confluence.dunerider_boots.info", "It have a Chance to be dropped from Husk.");
        add("item.confluence.fart_in_a_jar.info", "It have a Chance to be dropped from Ghost.");
        add("item.confluence.flipper.info", "It can be found in Chests in the Shipwreck.");
        add("item.confluence.flurry_boots.info", "It can be found in Igloo's chest.");
        add("item.confluence.frog_leg.info", "The Frog Leg have a Chance to be dropped from Frog.");
        add("item.confluence.hermes_boots.info", "It can be found in Chests in the Village Armorer.");
        add("item.confluence.lava_charm.info", "It have a Chance to be dropped from Blaze.");
        add("item.confluence.lucky_horseshoe.info", "It can be discovered in chests found within Desert Pyramids, End City, Jungle Pyramids, or Ancient Cities.");
        add("item.confluence.magiluminescence.info", "It can be found in End City Chests.");
        add("item.confluence.sailfish_boots.info", "It can be found in Shipwreck Chests.");
        add("item.confluence.sandstorm_in_a_bottle.info", "The Sandstorm in a Bottle is an accessory that can be found in Chests in the Desert Pyramid.");
        add("item.confluence.shiny_red_balloon.info", "When the player has the Hero of the Village effect, the librarian has a chance to give the player this item.");
        add("item.confluence.shoe_spikes.info", "It have a Chance to be dropped from Cave Spider.");
        add("item.confluence.step_stool.info", "You can use Step Stool to upgrade its Extra Step from Smithing Table");
        add("item.confluence.tabi.info", "It can be found in Chests in the Fortress.");
        add("item.confluence.tsunami_in_a_bottle.info", "It can be found in Shipwreck Chests");
        add("item.confluence.water_walking_boots.info", "It can be found in Ocean Ruins Chests.");
        add("item.confluence.copper_watch.info", "When equipped in an accessory slot or simply held in the inventory, a clock will appear in the upper-right corner of the playing screen, revealing the in-game time accurate to the last hour.");
        add("item.confluence.tin_watch.info", "When equipped in an accessory slot or simply held in the inventory, a clock will appear in the upper-right corner of the playing screen, revealing the in-game time accurate to the last hour. ");
        add("item.confluence.silver_watch.info", "When equipped in an accessory slot or simply held in the inventory, a clock will appear in the upper-right corner of the playing screen, revealing the in-game time accurate to the last half an hour.");
        add("item.confluence.tungsten_watch.info", "When equipped in an accessory slot or held in the inventory, a clock icon will appear in the upper-right corner of the playing screen, revealing the in-game time accurate to the last half-hour.");
        add("item.confluence.gold_watch.info", "When equipped in an accessory slot or simply held in the inventory, a clock will appear in the upper-right corner of the playing screen, revealing the in-game time accurate to the last minute. ");
        add("item.confluence.platinum_watch.info", "When equipped in an accessory slot or simply held in the inventory, a clock will appear in the upper-right corner of the playing screen, revealing the in-game time accurate to the last minute.");
        add("item.confluence.depth_meter.info", "The Depth Meter have a Chance to be dropped from Bats.");
        add("item.confluence.compass.info", "The Compass have a Chance to be dropped from Bats.");
        add("item.confluence.dps_meter.info", "The DPS Meter have a Chance to be dropped from Creeper.");
        add("item.confluence.fishermans_pocket_guide.info", "This item can be located in the chests found within Fisherman Villagers' houses.");
        add("item.confluence.life_form_analyzer.info", "The Lifeform Analyzer have a Chance to be dropped from Glow Squid.");
        add("item.confluence.metal_detector.info", "The Metal Detector have a Chance to be dropped from Warden.");
        add("item.confluence.radar.info", "The Radar have a Chance to be dropped from Bats.");
        add("item.confluence.sextant.info", "This item can be located in the chests found within Fisherman Villagers' houses.");
        add("item.confluence.tally_counter.info", "The Tally Counter a Chance to be dropped from Creeper.");
        add("item.confluence.weather_radio.info", "This item can be located in the chests found within Fisherman Villagers' houses.");
        add("item.confluence.band_of_regeneration.info", "The Band of Regeneration is an accessory that have a Chance to be dropped from Witch");
        add("item.confluence.angler_earring.info", "This item can be located in the chests found within Fisherman Villagers' houses.");
        add("item.confluence.brain_of_confusion.info", "The Brain of Confusion have a Chance to be dropped from Zombie Villager.");
        add("item.confluence.gravity_globe.info", "The Gravity Glob have a Chance to be dropped from Shulker.");
        add("item.confluence.hive_pack.info", "The Hive Pack have a Chance to be dropped from Bee.");
        add("item.confluence.royal_gel.info", "The Royal Gel have a Chance to be dropped from Slime.");
        add("item.confluence.shield_of_cthulhu.info", "It have a Chance to be dropped from Ravager.");
        add("item.confluence.worm_scarf.info", "When a player has a tamed cat, the cat may give the player this item when they wake up.");
        add("item.confluence.ancient_chisel.info", "The item can be pass the Archaeology to obtained.");
        add("item.confluence.brick_layer.info", "This item can be located in the chests found within Toolsmith Villagers' houses.");
        add("item.confluence.extendo_grip.info", "It can be discovered in chests found within Desert Pyramids.");
        add("item.confluence.portable_cement_mixer.info", "This item can be located in the chests found within Toolsmith Villagers' houses.");
        add("item.confluence.toolbelt.info", "This item can be located in the chests found within Toolsmith Villagers' houses.");
        add("item.confluence.toolbox.info", "The item can be located in the chests found within Toolsmith Villagers' houses.");
        add("item.confluence.flower_boots.info", "The Flower Boots have a Chance to be dropped from Moss Block.");
        add("item.confluence.treasure_magnet.info", "It can be discovered in chests found within Desert Pyramids, End City, Jungle Pyramids, or Ancient Cities.");
        add("item.confluence.bezoar.info", "It have a Chance to be dropped from Cave Spider.");
        add("item.confluence.black_belt.info", "It have a Chance to be dropped from Wither Skeleton.");
        add("item.confluence.blindfold.info", "It can be discovered in chests found within Ancient City.");
        add("item.confluence.cobalt_shield.info", "It have a Chance to be dropped from Ravager.");
        add("item.confluence.cross_necklace.info", "It have a Chance to be dropped from Evoker.");
        add("item.confluence.energy_bar.info", "It have a Chance to be dropped from Zombified Piglin.");
        add("item.confluence.eye_of_the_golem.info", "It can be discovered in chests found within Jungle Pyramids.");
        add("item.confluence.fast_clock.info", "It have a Chance to be dropped from Stray.");
        add("item.confluence.feral_claws.info", "It can be discovered in chests found within Jungle Pyramids.");
        add("item.confluence.flashlight.info", "It can be discovered in chests found within Stronghold.");
        add("item.confluence.flesh_knuckles.info", "It have a Chance to be dropped from Piglin Brute.");
        add("item.confluence.frozen_turtle_shell.info", "When the Turtle died for Freezing chance to dropped this item.");
        add("item.confluence.hand_drill.info", "It have a Chance to be dropped from Elder Guardian.");
        add("item.confluence.holy_water.info", "It have a Chance to be dropped from Wither Skeleton.");
        add("item.confluence.honey_comb.info", "The Honey Comb is a accessory which, when equipped, spawns 1–3 (or 1–4 with a Hive Pack equipped) bee projectiles which attack nearby enemies each time the player takes damage.");
        add("item.confluence.honey_comb.info2", "It also grants the Honey buff for 5 seconds after being damaged.");
        add("item.confluence.honey_comb.info3", "It have a Chance to be dropped from Bee.");
        add("item.confluence.magic_quiver.info", "This item have a Chance to be dropped from Wither Skeleton.");
        add("item.confluence.magma_stone.info", "It have a Chance to be dropped from Blaze.");
        add("item.confluence.moon_stone.info", "It have a Chance to be dropped from Phantom.");
        add("item.confluence.obsidian_rose.info", "It can be discovered in chests found within Bastion Remnant.");
        add("item.confluence.paladins_shield.info", "It to be dropped from Ender Dragon.");
        add("item.confluence.panic_necklace.info", "It can be found in Chests in the Dungeon.");
        add("item.confluence.putrid_scent.info", "It can be found in Chests in the Dungeon.");
        add("item.confluence.ranger_emblem.info", "It have a Chance to be dropped from Skeleton.");
        add("item.confluence.rifle_scope.info", "It have a Chance to be dropped from Enderman.");
        add("item.confluence.shackle.info", "It can be found in Chests in the Dungeon.");
        add("item.confluence.shark_tooth_necklace.info", "It has a chance to drop from Drowned.");
        add("item.confluence.shot_put.info", "It can be found in Chests in the Stronghold.");
        add("item.confluence.sorcerer_emblem.info", "It have a Chance to be dropped from Evoker.");
        add("item.confluence.star_cloak.info", "It can be discovered in chests found within Woodland Mansion.");
        add("item.confluence.sun_stone.info", "It have a Chance to be dropped from Blaze.");
        add("item.confluence.titan_glove.info", "It can be found in Chests in the Mineshaft.");
        add("item.confluence.trifold_map.info", "It can be found in Chests in the Stronghold Library.");
        add("item.confluence.vitamins.info", "It have a Chance to be dropped from Witch.");
        add("item.confluence.warrior_emblem.info", "It have a Chance to be dropped from Vindicator.");
        add("item.confluence.demon_heart.info", "It to be dropped from Wither.");
        add("item.confluence.berserkers_glove.info", "The Berserker's Glove is a Hardmode accessory crafted from the Power Glove and Flesh Knuckles, granting the abilities of both.");
        add("item.confluence.berserkers_glove.info2", "Autoswing for melee weapons and whips");

        add("death.attack.star_cloak", "%1$s was squashed by a falling star");

        add("attribute.name.generic.critical_chance", "Critical Chance");
        add("attribute.name.generic.ranged_velocity", "Ranged Velocity");
        add("attribute.name.generic.ranged_damage", "Ranged Damage");
        add("attribute.name.generic.dodge_chance", "Dodge Chance");
        add("attribute.name.generic.mining_speed", "Mining Speed");
        add("attribute.name.generic.aggro", "Aggro");
        add("attribute.name.generic.magic_damage", "Magic Damage");
        add("attribute.name.generic.armor_pass", "Armor Pass");
        add("attribute.name.generic.pickup_range", "Pickup Range");

        add("container.confluence.workshop", "Workshop");
        add("title.confluence.workshop", "Workshop");

        add("achievements.confluence.boots_of_the_hero.title", "Boots of the Hero");
        add("achievements.confluence.boots_of_the_hero.description", "Obtain the Terraspark Boots, forged from the finest boots of fire and ice.");

        ModItems.ITEMS.getEntries().forEach(item -> {
            Item item1 = item.get();
            if (item1 instanceof CustomName customName) add(item1, customName.getGenName());
            else add(item1, toTitleCase(item.getId().getPath()));
        });
        ModEntities.ENTITIES.getEntries().forEach(entity -> add(entity.get(), toTitleCase(entity.getId().getPath())));
        ModEffects.EFFECTS.getEntries().forEach(effect -> add(effect.get(), toTitleCase(effect.getId().getPath())));
    }

    private static String toTitleCase(String raw) {
        return Arrays.stream(raw.split("_"))
            .map(word -> Character.toUpperCase(word.charAt(0)) + word.substring(1).toLowerCase())
            .collect(Collectors.joining(" "));
    }
}
