org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.20
forge_version_range=[47.4.20,)
loader_version_range=[47,)
parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03

geckolib_version=4.8.3
curios_version=5.14.1+1.20.1
particlestorm_version=1.4.2.3
thr_dim_particle_version=1.2.0
the_trackers_version=1.20.1-0.2.6
portlib_version=1.2.1

#systemProp.http.proxyHost=localhost
#systemProp.http.proxyPort=7897
#systemProp.https.proxyHost=localhost
#systemProp.https.proxyPort=7897
